/**
 * Realistic Mock & Seeded Dataset for AROHA MoTA Scholarship System
 * Grounded in official Ministry of Tribal Affairs (MoTA) schemes:
 * - NFST (National Fellowship for Scheduled Tribe Students)
 * - NOS (National Overseas Scholarship for ST Candidates)
 */

import { Application, SchemeType, SystemStats } from '../types/scholarship';

export const SEEDED_APPLICATIONS: Application[] = [
  {
    id: 'app_nfst_001',
    applicationNumber: 'NFST/2025/0812',
    scheme: 'NFST',
    submittedAt: '2025-08-10T11:20:00Z',
    updatedAt: '2025-08-15T14:45:00Z',
    status: 'dbt_active',
    applicant: {
      fullName: 'Sowmika Helsiba Paramapogu',
      fatherName: 'P. Rameshwar',
      motherName: 'P. Sharada',
      gender: 'Female',
      dob: '1998-04-12',
      aadhaarNumber: 'XXXX-XXXX-8921',
      mobile: '+91 98480 12345',
      email: 'sowmikahelsibaparamapogu@gmail.com',
      stCommunity: 'Gond',
      state: 'Telangana',
      district: 'Adilabad',
      pincode: '504001',
      domicileState: 'Telangana',
      annualFamilyIncome: 340000,
      parentOccupation: 'Agriculture & Forest Produce Cooperative',
    },
    academic: {
      qualifyingDegree: 'M.Sc. in Biotechnology',
      qualifyingPercentage: 74.5,
      passingYear: 2024,
      institutionName: 'University of Hyderabad',
      targetProgram: 'Ph.D',
      specialization: 'Tribal Pharmacognosy & Indigenous Medicine',
      researchTopic: 'Bioactive compounds from sacred groves of Eastern Ghats and their ethnopharmacological validation',
      ugcNetRollNo: 'TG01004829',
      ugcNetScore: 98.42,
      ugcNetYear: '2024',
      isJrfQualified: true,
      phdRegistrationDate: '2024-09-01',
      guideName: 'Prof. K. V. Raman, Dept of Plant Sciences',
    },
    bankDetails: {
      accountHolderName: 'Sowmika Helsiba Paramapogu',
      accountNumber: '38192019482',
      ifscCode: 'SBIN0020491',
      bankName: 'State Bank of India',
      branchName: 'Adilabad Main Branch',
      isAadhaarSeeded: true,
    },
    documents: [
      {
        id: 'doc_caste_001',
        type: 'caste_certificate',
        name: 'ST_Caste_Certificate_Adilabad.pdf',
        size: 840210,
        uploadedAt: '2025-08-10T11:22:00Z',
        ocrStatus: 'verified',
        ocrConfidence: 98,
        extractedFields: {
          'Applicant Name': 'Sowmika Helsiba Paramapogu',
          'Community': 'Gond (Scheduled Tribe)',
          'Issuing Authority': 'Sub-Divisional Magistrate (SDM), Adilabad',
          'Certificate No': 'TG/ST/2023/009182',
          'Barcode Verification': 'Valid e-Pramaan Seal',
        },
      },
      {
        id: 'doc_marks_001',
        type: 'marksheet',
        name: 'MSc_Biotech_Consolidated_Marksheet.pdf',
        size: 1420500,
        uploadedAt: '2025-08-10T11:23:00Z',
        ocrStatus: 'verified',
        ocrConfidence: 96,
        extractedFields: {
          'Candidate Name': 'Sowmika Helsiba Paramapogu',
          'Degree': 'Master of Science (Biotechnology)',
          'Percentage': '74.5%',
          'University': 'University of Hyderabad',
        },
      },
      {
        id: 'doc_net_001',
        type: 'bonafide_certificate',
        name: 'UGC_NET_JRF_Award_Letter_2024.pdf',
        size: 512000,
        uploadedAt: '2025-08-10T11:24:00Z',
        ocrStatus: 'verified',
        ocrConfidence: 99,
        extractedFields: {
          'Roll Number': 'TG01004829',
          'Exam': 'UGC-NET Dec 2024 JRF',
          'Percentile': '98.42',
          'Subject': 'Life Sciences',
        },
      },
    ],
    aiAnalysis: {
      overallConfidence: 97,
      eligibilityPassed: true,
      requiresHumanReview: false,
      flags: [],
      riskScore: 'Low',
      meritScore: 92,
      verifiedFieldsCount: 16,
      totalFieldsCount: 16,
      summary: 'Candidate satisfies all NFST statutory parameters: Master degree aggregate (74.5% > 55%), UGC-NET JRF qualified (98.42 percentile), digital barcode verified ST Caste Certificate.',
    },
    deficiencies: [],
    scrutiny: {
      reviewedBy: 'Dr. Anand Verma, Scrutiny Officer (MoTA Desk-II)',
      reviewedAt: '2025-08-14T10:00:00Z',
      remarks: 'All documents verified against digilocker API. Approved for merit rank #14 in Biological Sciences category.',
      decision: 'approve',
      committeeRecommendation: 'Sanction awarded under NFST Regular JRF Fellowship.',
    },
    dbtDisbursements: [
      {
        trancheNumber: 1,
        description: 'JRF Monthly Fellowship + HRA (Months 1-3)',
        amount: 111000,
        currency: 'INR',
        status: 'disbursed',
        expectedDate: '2025-09-05',
        disbursedDate: '2025-09-03',
        utrNumber: 'PFMS202509038891024',
        dbtAccountLast4: '9482',
      },
      {
        trancheNumber: 2,
        description: 'Annual Contingency Grant (Humanities & Social Sciences/Life Sci)',
        amount: 20500,
        currency: 'INR',
        status: 'disbursed',
        expectedDate: '2025-09-20',
        disbursedDate: '2025-09-19',
        utrNumber: 'PFMS202509199920145',
        dbtAccountLast4: '9482',
      },
      {
        trancheNumber: 3,
        description: 'JRF Monthly Fellowship + HRA (Months 4-6)',
        amount: 111000,
        currency: 'INR',
        status: 'pfms_verified',
        expectedDate: '2025-12-05',
        dbtAccountLast4: '9482',
      },
    ],
  },
  {
    id: 'app_nos_002',
    applicationNumber: 'NOS/2025/0419',
    scheme: 'NOS',
    submittedAt: '2025-08-08T09:15:00Z',
    updatedAt: '2025-08-14T16:30:00Z',
    status: 'merit_listed',
    applicant: {
      fullName: 'Birsa Dev Munda',
      fatherName: 'Ganga Munda',
      motherName: 'Sukri Munda',
      gender: 'Male',
      dob: '1995-11-20',
      aadhaarNumber: 'XXXX-XXXX-4819',
      mobile: '+91 94311 55678',
      email: 'birsa.munda.nos@gov.in',
      stCommunity: 'Munda',
      state: 'Jharkhand',
      district: 'Khunti',
      pincode: '835210',
      domicileState: 'Jharkhand',
      annualFamilyIncome: 480000,
      parentOccupation: 'Primary School Teacher & Farmer',
    },
    academic: {
      qualifyingDegree: 'B.Tech in Metallurgical Engineering',
      qualifyingPercentage: 78.5,
      passingYear: 2023,
      institutionName: 'IIT Kharagpur',
      targetProgram: 'Masters',
      specialization: 'Advanced Materials & Sustainable Mining',
      foreignUniversityName: 'University of Oxford',
      countryOfStudy: 'United Kingdom',
      qsWorldRanking: 3,
      offerStatus: 'Unconditional',
      courseDurationMonths: 24,
      ieltsToeflScore: 'IELTS 8.0 (Overall)',
      researchTopic: 'Eco-efficient extraction processes in tribal mineral belts',
    },
    bankDetails: {
      accountHolderName: 'Birsa Dev Munda',
      accountNumber: '20938102941',
      ifscCode: 'BARB0KHUNTI',
      bankName: 'Bank of Baroda',
      branchName: 'Khunti Court Road',
      isAadhaarSeeded: true,
    },
    documents: [
      {
        id: 'doc_nos_caste',
        type: 'caste_certificate',
        name: 'Munda_ST_Certificate_Khunti.pdf',
        size: 910000,
        uploadedAt: '2025-08-08T09:18:00Z',
        ocrStatus: 'verified',
        ocrConfidence: 99,
        extractedFields: {
          'Name': 'Birsa Dev Munda',
          'Community': 'Munda (Scheduled Tribe)',
          'Issuing Authority': 'SDM Khunti',
          'Verified Date': '04-Feb-2022',
        },
      },
      {
        id: 'doc_nos_income',
        type: 'income_certificate',
        name: 'Family_Income_Cert_FY24_25.pdf',
        size: 670000,
        uploadedAt: '2025-08-08T09:19:00Z',
        ocrStatus: 'verified',
        ocrConfidence: 95,
        extractedFields: {
          'Gross Income': 'INR 4,80,000 / annum',
          'Financial Year': '2024-2025',
          'Issuing Authority': 'Circle Officer (CO), Khunti',
        },
      },
      {
        id: 'doc_nos_offer',
        type: 'offer_letter',
        name: 'Oxford_Unconditional_Offer_2025.pdf',
        size: 1840000,
        uploadedAt: '2025-08-08T09:20:00Z',
        ocrStatus: 'verified',
        ocrConfidence: 98,
        extractedFields: {
          'University': 'University of Oxford',
          'QS Ranking': 3,
          'Offer Type': 'Unconditional',
          'Degree': 'M.Sc. in Materials Science',
        },
      },
      {
        id: 'doc_nos_passport',
        type: 'passport',
        name: 'Indian_Passport_Birsa_Munda.pdf',
        size: 420000,
        uploadedAt: '2025-08-08T09:22:00Z',
        ocrStatus: 'verified',
        ocrConfidence: 99,
        extractedFields: {
          'Passport No': 'Z8194012',
          'Expiry': '10-Jul-2033',
        },
      },
    ],
    aiAnalysis: {
      overallConfidence: 98,
      eligibilityPassed: true,
      requiresHumanReview: false,
      flags: [],
      riskScore: 'Low',
      meritScore: 96,
      verifiedFieldsCount: 20,
      totalFieldsCount: 20,
      summary: 'Top Tier NOS Candidate. Oxford University (QS #3), Unconditional admission, Family income ₹4.8L (well below ₹8L ceiling), IIT Kharagpur 78.5% marks.',
    },
    deficiencies: [],
    scrutiny: {
      reviewedBy: 'Ms. S. Bhattacharya, Director (Scholarships), MoTA',
      reviewedAt: '2025-08-13T15:00:00Z',
      remarks: 'Outstanding profile. Recommended for Slot #1 under Engineering & Technology category for UK.',
      decision: 'approve',
    },
  },
  {
    id: 'app_nos_003',
    applicationNumber: 'NOS/2025/0932',
    scheme: 'NOS',
    submittedAt: '2025-08-12T16:40:00Z',
    updatedAt: '2025-08-15T11:10:00Z',
    status: 'in_scrutiny',
    applicant: {
      fullName: 'Rani Chameli Marandi',
      fatherName: 'Stephen Marandi',
      motherName: 'Elina Marandi',
      gender: 'Female',
      dob: '1997-08-25',
      aadhaarNumber: 'XXXX-XXXX-6102',
      mobile: '+91 97710 44321',
      email: 'rani.marandi.st@outlook.com',
      stCommunity: 'Santhal',
      state: 'Jharkhand',
      district: 'Dumka',
      pincode: '814101',
      domicileState: 'Jharkhand',
      annualFamilyIncome: 760000,
      parentOccupation: 'Government PSU Employee & Horticulture',
    },
    academic: {
      qualifyingDegree: 'B.Sc. (Hons) in Environmental Science',
      qualifyingPercentage: 66.8,
      passingYear: 2023,
      institutionName: 'St. Xavier’s College, Ranchi',
      targetProgram: 'Masters',
      specialization: 'Climate Change Finance & Policy',
      foreignUniversityName: 'Imperial College London',
      countryOfStudy: 'United Kingdom',
      qsWorldRanking: 6,
      offerStatus: 'Unconditional',
      courseDurationMonths: 12,
    },
    bankDetails: {
      accountHolderName: 'Rani Chameli Marandi',
      accountNumber: '48201948201',
      ifscCode: 'PUNB0182000',
      bankName: 'Punjab National Bank',
      branchName: 'Dumka Branch',
      isAadhaarSeeded: true,
    },
    documents: [
      {
        id: 'doc_marandi_caste',
        type: 'caste_certificate',
        name: 'Santhal_Certificate_Dumka.pdf',
        size: 790000,
        uploadedAt: '2025-08-12T16:42:00Z',
        ocrStatus: 'verified',
        ocrConfidence: 96,
        extractedFields: {
          'Name': 'Rani Chameli Marandi',
          'Tribe': 'Santhal (ST)',
        },
      },
      {
        id: 'doc_marandi_income',
        type: 'income_certificate',
        name: 'Income_Certificate_2024.pdf',
        size: 820000,
        uploadedAt: '2025-08-12T16:43:00Z',
        ocrStatus: 'flagged',
        ocrConfidence: 74,
        extractedFields: {
          'Annual Income': 'INR 7,60,000',
          'Notice': 'Within 5% of statutory Rs 8,00,000 threshold',
        },
        mismatches: [
          'Annual family income (₹7.60 Lakh) is borderline near the ₹8.00 Lakh upper ceiling — requires salary slip cross-verification.',
        ],
      },
      {
        id: 'doc_marandi_offer',
        type: 'offer_letter',
        name: 'Imperial_College_Offer.pdf',
        size: 1200000,
        uploadedAt: '2025-08-12T16:44:00Z',
        ocrStatus: 'verified',
        ocrConfidence: 98,
        extractedFields: {
          'University': 'Imperial College London',
          'QS Ranking': 6,
          'Offer Type': 'Unconditional',
        },
      },
      {
        id: 'doc_marandi_passport',
        type: 'passport',
        name: 'Passport_Rani_Marandi.pdf',
        size: 550000,
        uploadedAt: '2025-08-12T16:45:00Z',
        ocrStatus: 'verified',
        ocrConfidence: 97,
        extractedFields: {
          'Passport No': 'K9182741',
        },
      },
    ],
    aiAnalysis: {
      overallConfidence: 74,
      eligibilityPassed: true,
      requiresHumanReview: true,
      flags: [
        'Income is within 5% of statutory ₹8.00 Lakh ceiling (₹7,60,000 reported).',
        'Parent employment is PSU — requires Form 16 / ITR tax assessment verification.',
      ],
      riskScore: 'Medium',
      meritScore: 84,
      verifiedFieldsCount: 17,
      totalFieldsCount: 20,
      summary: 'Candidate qualifies academically with Imperial College unconditional offer (QS #6), but income is near upper cutoff limit. Scrutiny officer sign-off needed.',
    },
    deficiencies: [],
  },
  {
    id: 'app_nfst_004',
    applicationNumber: 'NFST/2025/1104',
    scheme: 'NFST',
    submittedAt: '2025-08-14T14:10:00Z',
    updatedAt: '2025-08-15T09:30:00Z',
    status: 'flagged_deficiency',
    applicant: {
      fullName: 'Jemimah Khasi',
      fatherName: 'Lapang Khasi',
      motherName: 'Grace Khasi',
      gender: 'Female',
      dob: '1999-02-14',
      aadhaarNumber: 'XXXX-XXXX-3890',
      mobile: '+91 94361 77890',
      email: 'jemimah.khasi@nehu.ac.in',
      stCommunity: 'Khasi',
      state: 'Meghalaya',
      district: 'East Khasi Hills',
      pincode: '793022',
      domicileState: 'Meghalaya',
      annualFamilyIncome: 290000,
      parentOccupation: 'Handicrafts & Agriculture',
    },
    academic: {
      qualifyingDegree: 'M.A. in Linguistics',
      qualifyingPercentage: 69.2,
      passingYear: 2024,
      institutionName: 'North-Eastern Hill University (NEHU), Shillong',
      targetProgram: 'Ph.D',
      specialization: 'Mon-Khmer Endangered Dialects Documentation',
      researchTopic: 'Phonological documentation and revival of endangered War-Jaintia and Khasi tribal varieties',
      ugcNetRollNo: 'ML01002910',
      ugcNetScore: 94.1,
      ugcNetYear: '2024',
      isJrfQualified: true,
    },
    bankDetails: {
      accountHolderName: 'Jemimah Khasi',
      accountNumber: '10928192049',
      ifscCode: 'SBIN0001815',
      bankName: 'State Bank of India',
      branchName: 'NEHU Campus Shillong',
      isAadhaarSeeded: true,
    },
    documents: [
      {
        id: 'doc_khasi_caste',
        type: 'caste_certificate',
        name: 'ST_Certificate_Old_Format.pdf',
        size: 610000,
        uploadedAt: '2025-08-14T14:12:00Z',
        ocrStatus: 'mismatch',
        ocrConfidence: 54,
        extractedFields: {
          'Name': 'Jemimah Lapang',
          'Community': 'Khasi',
          'Date': 'Issued: 2017 (Manual handwritten register without digital barcode)',
        },
        mismatches: [
          'Surname on certificate reads "Jemimah Lapang" whereas application records "Jemimah Khasi".',
          'Certificate lacks the required e-District digital verification QR/barcode as mandated in MoTA 2024 circular.',
        ],
      },
      {
        id: 'doc_khasi_marks',
        type: 'marksheet',
        name: 'MA_Linguistics_Marksheet.pdf',
        size: 980000,
        uploadedAt: '2025-08-14T14:14:00Z',
        ocrStatus: 'verified',
        ocrConfidence: 98,
        extractedFields: {
          'Percentage': '69.2%',
          'University': 'NEHU Shillong',
        },
      },
      {
        id: 'doc_khasi_net',
        type: 'bonafide_certificate',
        name: 'UGC_NET_June2024.pdf',
        size: 490000,
        uploadedAt: '2025-08-14T14:15:00Z',
        ocrStatus: 'verified',
        ocrConfidence: 95,
        extractedFields: {
          'Roll No': 'ML01002910',
          'Percentile': '94.1',
        },
      },
    ],
    aiAnalysis: {
      overallConfidence: 58,
      eligibilityPassed: false,
      requiresHumanReview: true,
      flags: [
        'Critical Defect: Name mismatch on ST Certificate ("Jemimah Lapang" vs "Jemimah Khasi").',
        'Digital barcode/e-Pramaan seal missing on uploaded ST document.',
      ],
      riskScore: 'High',
      meritScore: 78,
      verifiedFieldsCount: 11,
      totalFieldsCount: 16,
      summary: 'AI OCR flagged document discrepancy: ST Certificate lacks digital authentication code and has name variation with father surname.',
    },
    deficiencies: [
      {
        id: 'def_khasi_001',
        documentId: 'doc_khasi_caste',
        field: 'caste_certificate',
        title: 'Deficient ST Caste Certificate (Format & Name Discrepancy)',
        description: 'Your uploaded ST Caste Certificate (dated 2017) is an older non-digital format and records the name as "Jemimah Lapang" instead of "Jemimah Khasi". Please upload an updated digitally-signed ST certificate from the Deputy Commissioner (DC) East Khasi Hills or submit an official name change affidavit.',
        severity: 'critical',
        issuedAt: '2025-08-15T09:30:00Z',
        isResolved: false,
      },
    ],
  },
  {
    id: 'app_nfst_005',
    applicationNumber: 'NFST/2025/0551',
    scheme: 'NFST',
    submittedAt: '2025-08-13T10:05:00Z',
    updatedAt: '2025-08-15T12:00:00Z',
    status: 'in_scrutiny',
    applicant: {
      fullName: 'Kishan Lal Bhil',
      fatherName: 'Motiram Bhil',
      motherName: 'Geeta Bhil',
      gender: 'Male',
      dob: '1996-06-18',
      aadhaarNumber: 'XXXX-XXXX-9912',
      mobile: '+91 94140 28192',
      email: 'kishan.bhil@mlsu.ac.in',
      stCommunity: 'Bhil',
      state: 'Rajasthan',
      district: 'Udaipur',
      pincode: '313001',
      domicileState: 'Rajasthan',
      annualFamilyIncome: 210000,
      parentOccupation: 'Traditional Agriculture',
    },
    academic: {
      qualifyingDegree: 'M.Sc. in Forestry',
      qualifyingPercentage: 71.0,
      passingYear: 2023,
      institutionName: 'Mohanlal Sukhadia University (MLSU), Udaipur',
      targetProgram: 'Ph.D',
      specialization: 'Forest Ecology & Tribal Agroforestry',
      researchTopic: 'Impact of climate variability on Mahua and Tendu leaf yields in South Rajasthan tribal belt',
      ugcNetRollNo: 'RJ04001928',
      ugcNetScore: 91.8,
      ugcNetYear: '2024',
      isJrfQualified: true,
    },
    bankDetails: {
      accountHolderName: 'Kishan Lal Bhil',
      accountNumber: '39102910491',
      ifscCode: 'SBIN0001533',
      bankName: 'State Bank of India',
      branchName: 'MLSU Campus Udaipur',
      isAadhaarSeeded: true,
    },
    documents: [
      {
        id: 'doc_bhil_caste',
        type: 'caste_certificate',
        name: 'Bhil_ST_Cert_Udaipur.pdf',
        size: 730000,
        uploadedAt: '2025-08-13T10:07:00Z',
        ocrStatus: 'verified',
        ocrConfidence: 97,
        extractedFields: {
          'Name': 'Kishan Lal Bhil',
          'Community': 'Bhil (Scheduled Tribe)',
          'Authority': 'Tehsildar Girwa, Udaipur',
        },
      },
      {
        id: 'doc_bhil_marks',
        type: 'marksheet',
        name: 'MSc_Forestry_Marksheet.pdf',
        size: 910000,
        uploadedAt: '2025-08-13T10:08:00Z',
        ocrStatus: 'verified',
        ocrConfidence: 94,
        extractedFields: {
          'Percentage': '71.0%',
        },
      },
      {
        id: 'doc_bhil_bonafide',
        type: 'bonafide_certificate',
        name: 'Bonafide_Dept_of_Botany_MLSU.pdf',
        size: 580000,
        uploadedAt: '2025-08-13T10:09:00Z',
        ocrStatus: 'verified',
        ocrConfidence: 95,
        extractedFields: {
          'Department': 'Dept of Forestry & Environmental Sciences',
          'Status': 'Enrolled for Full-Time Ph.D',
        },
      },
    ],
    aiAnalysis: {
      overallConfidence: 94,
      eligibilityPassed: true,
      requiresHumanReview: false,
      flags: [],
      riskScore: 'Low',
      meritScore: 89,
      verifiedFieldsCount: 16,
      totalFieldsCount: 16,
      summary: 'Candidate documents verified without error. Eligible under NFST Agricultural & Environmental Sciences quota.',
    },
    deficiencies: [],
  },
  {
    id: 'app_nos_006',
    applicationNumber: 'NOS/2025/0108',
    scheme: 'NOS',
    submittedAt: '2025-08-05T08:30:00Z',
    updatedAt: '2025-08-12T14:15:00Z',
    status: 'approved',
    applicant: {
      fullName: 'Anil Kumar Oraon',
      fatherName: 'Bande Oraon',
      motherName: 'Fulmani Oraon',
      gender: 'Male',
      dob: '1996-03-09',
      aadhaarNumber: 'XXXX-XXXX-1940',
      mobile: '+91 98260 99482',
      email: 'anil.oraon@alumni.iitd.ac.in',
      stCommunity: 'Oraon',
      state: 'Chhattisgarh',
      district: 'Jashpur',
      pincode: '496331',
      domicileState: 'Chhattisgarh',
      annualFamilyIncome: 420000,
      parentOccupation: 'Rural Cooperative Secretary',
    },
    academic: {
      qualifyingDegree: 'B.Tech in Computer Science',
      qualifyingPercentage: 81.2,
      passingYear: 2022,
      institutionName: 'IIT Delhi',
      targetProgram: 'Masters',
      specialization: 'Artificial Intelligence & Low-Resource NLP',
      foreignUniversityName: 'National University of Singapore (NUS)',
      countryOfStudy: 'Singapore',
      qsWorldRanking: 8,
      offerStatus: 'Unconditional',
      courseDurationMonths: 18,
      researchTopic: 'Multilingual speech models for Dravidian and Kurukh tribal languages',
    },
    bankDetails: {
      accountHolderName: 'Anil Kumar Oraon',
      accountNumber: '40918201948',
      ifscCode: 'CBIN0281940',
      bankName: 'Central Bank of India',
      branchName: 'Jashpur Nagar',
      isAadhaarSeeded: true,
    },
    documents: [
      {
        id: 'doc_oraon_caste',
        type: 'caste_certificate',
        name: 'Oraon_ST_Certificate_Jashpur.pdf',
        size: 890000,
        uploadedAt: '2025-08-05T08:32:00Z',
        ocrStatus: 'verified',
        ocrConfidence: 99,
        extractedFields: {
          'Name': 'Anil Kumar Oraon',
          'Community': 'Oraon (ST)',
        },
      },
      {
        id: 'doc_oraon_income',
        type: 'income_certificate',
        name: 'Income_Certificate_FY24.pdf',
        size: 710000,
        uploadedAt: '2025-08-05T08:33:00Z',
        ocrStatus: 'verified',
        ocrConfidence: 97,
        extractedFields: {
          'Income': 'INR 4,20,000 / annum',
        },
      },
      {
        id: 'doc_oraon_offer',
        type: 'offer_letter',
        name: 'NUS_MComp_Offer_Letter.pdf',
        size: 1450000,
        uploadedAt: '2025-08-05T08:34:00Z',
        ocrStatus: 'verified',
        ocrConfidence: 99,
        extractedFields: {
          'University': 'National University of Singapore',
          'QS Ranking': 8,
          'Offer': 'Unconditional Admission',
        },
      },
    ],
    aiAnalysis: {
      overallConfidence: 99,
      eligibilityPassed: true,
      requiresHumanReview: false,
      flags: [],
      riskScore: 'Low',
      meritScore: 98,
      verifiedFieldsCount: 19,
      totalFieldsCount: 19,
      summary: 'Verified unconditionally against NUS offer (QS #8), IIT Delhi 81.2% aggregate, and valid ST certificate.',
    },
    deficiencies: [],
    scrutiny: {
      reviewedBy: 'Dr. R. K. Meena, Additional Secretary (Tribal Development)',
      reviewedAt: '2025-08-11T16:00:00Z',
      remarks: 'Highest merit in Science & Technology group. Sanction granted.',
      decision: 'approve',
    },
  },
];

export const INITIAL_SYSTEM_STATS: SystemStats = {
  totalApplications: 1482,
  verifiedPercentage: 88.4,
  averageProcessingDays: 3.8,
  pendingDeficiencies: 47,
  aiPreVerifiedCount: 1394,
  aiPreVerifiedPercentage: 94.1,
  approvedCount: 740,
  meritListedCount: 305,
  dbtActiveCount: 685,
  dbtTotalDisbursedInr: 248500000,
  schemeBreakdown: {
    nfstCount: 1140,
    nosCount: 342,
    NFST: 1140,
    NOS: 342,
  },
  stateWiseCount: {
    'Jharkhand': 312,
    'Odisha': 278,
    'Madhya Pradesh': 245,
    'Chhattisgarh': 189,
    'Telangana': 164,
    'Meghalaya': 118,
    'Assam': 98,
    'Rajasthan': 78,
  },
  stateDistribution: {
    'Jharkhand': 312,
    'Odisha': 278,
    'Madhya Pradesh': 245,
    'Chhattisgarh': 189,
    'Telangana': 164,
    'Meghalaya': 118,
    'Assam': 98,
    'Rajasthan': 78,
  },
};

export const FUNNEL_DATA = [
  { stage: 'Applications Submitted', count: 1482, percent: '100%' },
  { stage: 'AI OCR Document Checked', count: 1394, percent: '94.1%' },
  { stage: 'Rule Engine Verified', count: 1210, percent: '81.6%' },
  { stage: 'Scrutiny Committee Cleared', count: 1045, percent: '70.5%' },
  { stage: 'Merit Ranked & Selected', count: 770, percent: '51.9%' },
  { stage: 'DBT Direct Disbursal Active', count: 685, percent: '46.2%' },
];

export const PROCESSING_TRENDS = [
  { week: 'Wk 1', manualAvgDays: 14.5, aiSystemAvgDays: 5.2, deficiencyResolutionDays: 6.8 },
  { week: 'Wk 2', manualAvgDays: 13.8, aiSystemAvgDays: 4.6, deficiencyResolutionDays: 5.4 },
  { week: 'Wk 3', manualAvgDays: 14.2, aiSystemAvgDays: 3.9, deficiencyResolutionDays: 4.1 },
  { week: 'Wk 4', manualAvgDays: 15.0, aiSystemAvgDays: 3.8, deficiencyResolutionDays: 3.2 },
];
