import { Application, SchemeType, SchemeRuleConfig } from '../types/scholarship';
import { SEEDED_APPLICATIONS } from './mockData';
import { evaluateApplication } from './ruleEngine';
import { MASTER_36_INDIAN_STATES } from '../data/indianStates';

export interface PresetScenario {
  id: string;
  name: string;
  badge: string;
  badgeColor: string;
  category: string;
  description: string;
  parameters: {
    incomeCeiling: number;
    marksThreshold: number;
    totalSlots: number;
    femaleQuota: number;
  };
  additionalApplications: Application[];
  keyHighlights: string[];
}

// 1. Initial Baseline: STRICTLY EMPTY (Zero false/mock data before user adds preset)
export const BASELINE_APPLICATIONS: Application[] = [];

// Curated Spectrum Cohort: 100% Correct Person, 20% Test Candidate, and Calibrated Mistake Reductions
export const COHORT_20PCT_CONFIDENCE_SPECTRUM: Application[] = [
  {
    id: 'app_spec_100',
    applicationNumber: 'NFST/2026/PERFECT-100',
    scheme: 'NFST',
    submittedAt: '2026-02-01T10:00:00Z',
    updatedAt: '2026-02-01T10:00:00Z',
    status: 'dbt_active',
    applicant: {
      fullName: 'Ananya Soren',
      fatherName: 'Prakash Soren',
      motherName: 'Sunita Soren',
      gender: 'Female',
      dob: '1998-04-12',
      aadhaarNumber: 'XXXX-XXXX-8921',
      mobile: '+91 94311 55678',
      email: 'ananya.soren@jnu.ac.in',
      stCommunity: 'Santhal',
      state: 'Jharkhand',
      district: 'Dumka',
      pincode: '814101',
      domicileState: 'Jharkhand',
      annualFamilyIncome: 220000,
      parentOccupation: 'Primary School Teacher & Agriculture',
    },
    academic: {
      qualifyingDegree: 'M.Sc. in Biotechnology',
      qualifyingPercentage: 88.5,
      passingYear: 2024,
      institutionName: 'Jawaharlal Nehru University (JNU), New Delhi',
      targetProgram: 'Ph.D',
      specialization: 'Indigenous Medicinal Plant Genetics',
      researchTopic: 'Molecular characterization of bioactive flavonoids in Santhal tribal herbal remedies',
      ugcNetRollNo: 'JH04001923',
      ugcNetScore: 99.2,
      ugcNetYear: '2024',
      isJrfQualified: true,
    },
    bankDetails: {
      accountHolderName: 'Ananya Soren',
      accountNumber: '39201940192',
      ifscCode: 'SBIN0000072',
      bankName: 'State Bank of India',
      branchName: 'Dumka Main Branch',
      isAadhaarSeeded: true,
    },
    documents: [
      {
        id: 'doc_100_caste',
        type: 'caste_certificate',
        name: 'Santhal_ST_Certificate_Official.pdf',
        size: 1450000,
        uploadedAt: '2026-02-01T10:05:00Z',
        ocrStatus: 'verified',
        ocrConfidence: 100,
        extractedFields: {
          'Candidate Name': 'Ananya Soren',
          'Father Name': 'Prakash Soren',
          'Tribe / Category': 'Santhal (Scheduled Tribe)',
          'Issuing Authority': 'Sub-Divisional Officer (Civil), Dumka',
        },
      },
      {
        id: 'doc_100_marks',
        type: 'marksheet',
        name: 'MSc_Biotech_Transcript_JNU.pdf',
        size: 2100000,
        uploadedAt: '2026-02-01T10:06:00Z',
        ocrStatus: 'verified',
        ocrConfidence: 100,
        extractedFields: {
          'Candidate Name': 'Ananya Soren',
          'Aggregate Percentage': '88.5%',
          'Degree Awarded': 'Master of Science with Distinction',
        },
      },
      {
        id: 'doc_100_bonafide',
        type: 'bonafide_certificate',
        name: 'UGC_NET_JRF_Award_Letter.pdf',
        size: 1200000,
        uploadedAt: '2026-02-01T10:07:00Z',
        ocrStatus: 'verified',
        ocrConfidence: 100,
        extractedFields: {
          'Fellowship Award': 'Junior Research Fellowship (JRF)',
          'Percentile Score': '99.2',
        },
      },
    ],
    aiAnalysis: {
      overallConfidence: 100,
      eligibilityPassed: true,
      requiresHumanReview: false,
      flags: ['100% Exemplary Dossier: High Research Merit & Full Compliance'],
      riskScore: 'Low',
      meritScore: 100,
      verifiedFieldsCount: 16,
      totalFieldsCount: 16,
      summary: '100% Verified Candidate. All statutory criteria, academic cutoffs, and credentials verified with zero discrepancies.',
    },
    deficiencies: [],
  },
  {
    id: 'app_spec_020',
    applicationNumber: 'NFST/2026/TEST-20PCT',
    scheme: 'NFST',
    submittedAt: '2026-02-03T14:15:00Z',
    updatedAt: '2026-02-03T14:15:00Z',
    status: 'flagged_deficiency',
    applicant: {
      fullName: 'Vikram Munda',
      fatherName: 'Sukhram Munda',
      motherName: 'Maino Devi',
      gender: 'Male',
      dob: '1997-09-18',
      aadhaarNumber: 'XXXX-XXXX-4912',
      mobile: '+91 98351 90214',
      email: 'vikram.munda.test@gmail.com',
      stCommunity: 'Munda',
      state: 'Jharkhand',
      district: 'Khunti',
      pincode: '835210',
      domicileState: 'Jharkhand',
      annualFamilyIncome: 380000,
      parentOccupation: 'Farmer',
    },
    academic: {
      qualifyingDegree: 'Bachelor of Arts (General)',
      qualifyingPercentage: 46.2,
      passingYear: 2023,
      institutionName: 'Ranchi Regional College',
      targetProgram: 'Ph.D',
      specialization: 'Tribal Folklore',
      ugcNetRollNo: 'JH02009182',
      ugcNetScore: 41.0,
      ugcNetYear: '2023',
      isJrfQualified: false,
    },
    bankDetails: {
      accountHolderName: 'Vikram Munda',
      accountNumber: '29104910291',
      ifscCode: 'SBIN0001092',
      bankName: 'State Bank of India',
      branchName: 'Khunti Branch',
      isAadhaarSeeded: false,
    },
    documents: [
      {
        id: 'doc_20_caste',
        type: 'caste_certificate',
        name: 'Damaged_Caste_Certificate.jpg',
        size: 980000,
        uploadedAt: '2026-02-03T14:20:00Z',
        ocrStatus: 'mismatch',
        ocrConfidence: 20,
        mismatches: [
          'Candidate Name Mismatch: Document shows "Vikram Kumar" instead of "Vikram Munda"',
          'Community Mismatch: Certificate indicates Kurmi (OBC) category instead of Scheduled Tribe (Munda)',
        ],
        extractedFields: {
          'Candidate Name': 'Vikram Kumar',
          'Category Recorded': 'OBC (Kurmi)',
        },
      },
      {
        id: 'doc_20_marks',
        type: 'marksheet',
        name: 'BA_Marksheet_Scanned.pdf',
        size: 1100000,
        uploadedAt: '2026-02-03T14:22:00Z',
        ocrStatus: 'mismatch',
        ocrConfidence: 20,
        mismatches: [
          'Qualifying percentage (46.2%) fails statutory MoTA cutoff of 55.0% (Discrepancy: -8.8%)',
        ],
        extractedFields: {
          'Aggregate Percentage': '46.2%',
          'Division': 'Third Division',
        },
      },
    ],
    aiAnalysis: {
      overallConfidence: 20,
      eligibilityPassed: false,
      requiresHumanReview: true,
      flags: [
        'Qualifying percentage (46.2%) is below statutory cutoff of 55.0%',
        'Candidate Name Mismatch on Caste Certificate (Vikram Kumar vs Vikram Munda)',
        'Caste category records OBC instead of ST Munda',
        'Missing mandatory Ph.D Bonafide / NET JRF scorecard',
      ],
      riskScore: 'High',
      meritScore: 35,
      verifiedFieldsCount: 3,
      totalFieldsCount: 16,
      summary: 'Ineligible. Exactly 20% verification confidence. Fails statutory 55% academic threshold with multiple critical caste credential discrepancies.',
    },
    deficiencies: [
      {
        id: 'def_20_marks',
        field: 'qualifyingPercentage',
        title: 'Qualifying Score Below Scheme Cutoff',
        description: 'Candidate scored 46.2%, which is 8.8% below the mandatory MoTA 55.0% statutory cutoff.',
        severity: 'critical',
        issuedAt: '2026-02-03T14:25:00Z',
        isResolved: false,
      },
      {
        id: 'def_20_caste',
        field: 'caste_certificate',
        title: 'Caste Certificate Discrepancy',
        description: 'Uploaded certificate indicates Kurmi (OBC) category and records name as "Vikram Kumar". Valid ST Munda certificate required.',
        severity: 'critical',
        issuedAt: '2026-02-03T14:25:00Z',
        isResolved: false,
      },
      {
        id: 'def_20_bonafide',
        field: 'bonafide_certificate',
        title: 'Missing Ph.D Bonafide Certificate',
        description: 'Mandatory bonafide research enrollment certificate not provided.',
        severity: 'critical',
        issuedAt: '2026-02-03T14:25:00Z',
        isResolved: false,
      },
    ],
  },
  {
    id: 'app_spec_084',
    applicationNumber: 'NFST/2026/COHORT-84PCT',
    scheme: 'NFST',
    submittedAt: '2026-02-04T09:10:00Z',
    updatedAt: '2026-02-04T09:10:00Z',
    status: 'in_scrutiny',
    applicant: {
      fullName: 'Sunita Tirkey',
      fatherName: 'P. Rameshwar Tirkey',
      motherName: 'Basanti Tirkey',
      gender: 'Female',
      dob: '1999-07-25',
      aadhaarNumber: 'XXXX-XXXX-6721',
      mobile: '+91 97711 44321',
      email: 'sunita.tirkey@cuo.ac.in',
      stCommunity: 'Oraon',
      state: 'Odisha',
      district: 'Sundargarh',
      pincode: '770001',
      domicileState: 'Odisha',
      annualFamilyIncome: 280000,
      parentOccupation: 'Agriculture',
    },
    academic: {
      qualifyingDegree: 'M.A. in Tribal Studies',
      qualifyingPercentage: 74.0,
      passingYear: 2024,
      institutionName: 'Central University of Odisha',
      targetProgram: 'Ph.D',
      specialization: 'Kurukh Indigenous Language Revitalization',
      researchTopic: 'Documentation of endangered oral songs and linguistics of Kurukh (Oraon) elders',
      ugcNetRollNo: 'OD02003819',
      ugcNetScore: 88.5,
      ugcNetYear: '2024',
      isJrfQualified: true,
    },
    bankDetails: {
      accountHolderName: 'Sunita Tirkey',
      accountNumber: '49102910482',
      ifscCode: 'SBIN0000182',
      bankName: 'State Bank of India',
      branchName: 'Sundargarh Main Branch',
      isAadhaarSeeded: true,
    },
    documents: [
      {
        id: 'doc_84_caste',
        type: 'caste_certificate',
        name: 'Oraon_ST_Certificate.pdf',
        size: 1300000,
        uploadedAt: '2026-02-04T09:15:00Z',
        ocrStatus: 'verified',
        ocrConfidence: 92,
        extractedFields: {
          'Candidate Name': 'Sunita Tirkey',
          'Father Name': 'Rameshwar Tirkey',
          'Tribe': 'Oraon (Scheduled Tribe)',
        },
      },
      {
        id: 'doc_84_marks',
        type: 'marksheet',
        name: 'MA_Marksheet.pdf',
        size: 1400000,
        uploadedAt: '2026-02-04T09:16:00Z',
        ocrStatus: 'verified',
        ocrConfidence: 90,
        extractedFields: {
          'Aggregate Percentage': '74.0%',
        },
      },
    ],
    aiAnalysis: {
      overallConfidence: 84,
      eligibilityPassed: true,
      requiresHumanReview: false,
      flags: [
        'Minor formatting notice: Father initial in form (P. Rameshwar) expanded as Rameshwar in certificate (-6% confidence)',
      ],
      riskScore: 'Low',
      meritScore: 84,
      verifiedFieldsCount: 14,
      totalFieldsCount: 16,
      summary: 'High merit scholar (84% confidence). Passed all statutory cutoffs with a minor clerical father-name initial expansion note.',
    },
    deficiencies: [],
  },
  {
    id: 'app_spec_062',
    applicationNumber: 'NOS/2026/COHORT-62PCT',
    scheme: 'NOS',
    submittedAt: '2026-02-05T11:30:00Z',
    updatedAt: '2026-02-05T11:30:00Z',
    status: 'in_scrutiny',
    applicant: {
      fullName: 'Prakash Gond',
      fatherName: 'Mangal Gond',
      motherName: 'Rukmini Gond',
      gender: 'Male',
      dob: '1996-11-04',
      aadhaarNumber: 'XXXX-XXXX-3419',
      mobile: '+91 94251 77890',
      email: 'prakash.gond@bhopal-univ.ac.in',
      stCommunity: 'Gond',
      state: 'Madhya Pradesh',
      district: 'Mandla',
      pincode: '481661',
      domicileState: 'Madhya Pradesh',
      annualFamilyIncome: 775000,
      parentOccupation: 'Government Clerk',
    },
    academic: {
      qualifyingDegree: 'Master of Technology (M.Tech)',
      qualifyingPercentage: 66.5,
      passingYear: 2023,
      institutionName: 'MANIT Bhopal',
      targetProgram: 'Ph.D',
      foreignUniversityName: 'University of Wollongong, Australia',
      qsWorldRanking: 162,
      offerStatus: 'Conditional',
      specialization: 'Renewable Microgrid Infrastructure',
    },
    bankDetails: {
      accountHolderName: 'Prakash Gond',
      accountNumber: '58192019482',
      ifscCode: 'UBIN0531201',
      bankName: 'Union Bank of India',
      branchName: 'Mandla Branch',
      isAadhaarSeeded: true,
    },
    documents: [
      {
        id: 'doc_62_income',
        type: 'income_certificate',
        name: 'Tahsildar_Income_2024.pdf',
        size: 1200000,
        uploadedAt: '2026-02-05T11:35:00Z',
        ocrStatus: 'verified',
        ocrConfidence: 75,
        extractedFields: {
          'Annual Family Income': '₹7,75,000',
        },
      },
      {
        id: 'doc_62_offer',
        type: 'offer_letter',
        name: 'Wollongong_Offer_Letter.pdf',
        size: 1600000,
        uploadedAt: '2026-02-05T11:36:00Z',
        ocrStatus: 'verified',
        ocrConfidence: 70,
        extractedFields: {
          'Offer Status': 'Conditional (IELTS 7.0 required prior to visa)',
          'QS Ranking': '162',
        },
      },
    ],
    aiAnalysis: {
      overallConfidence: 62,
      eligibilityPassed: true,
      requiresHumanReview: true,
      flags: [
        'Annual income (₹7.75 Lakhs) is within 5% of statutory ₹8.00 Lakh ceiling (-18% confidence)',
        'Foreign university offer is Conditional on language test (-20% confidence)',
      ],
      riskScore: 'Medium',
      meritScore: 68,
      verifiedFieldsCount: 11,
      totalFieldsCount: 16,
      summary: 'Borderline NOS candidate (62% confidence). Moderate mistakes: Family income near upper boundary and conditional foreign offer letter.',
    },
    deficiencies: [],
  },
  {
    id: 'app_spec_045',
    applicationNumber: 'NFST/2026/COHORT-45PCT',
    scheme: 'NFST',
    submittedAt: '2026-02-06T15:20:00Z',
    updatedAt: '2026-02-06T15:20:00Z',
    status: 'flagged_deficiency',
    applicant: {
      fullName: 'Rajeshwari Bhil',
      fatherName: 'Bhanwar Singh Bhil',
      motherName: 'Geeta Bhil',
      gender: 'Female',
      dob: '1998-08-14',
      aadhaarNumber: 'XXXX-XXXX-9912',
      mobile: '+91 94140 12891',
      email: 'rajeshwari.bhil@mlsu.ac.in',
      stCommunity: 'Bhil',
      state: 'Rajasthan',
      district: 'Banswara',
      pincode: '327001',
      domicileState: 'Rajasthan',
      annualFamilyIncome: 310000,
      parentOccupation: 'Agriculture',
    },
    academic: {
      qualifyingDegree: 'Master of Arts (Economics)',
      qualifyingPercentage: 53.5,
      passingYear: 2024,
      institutionName: 'Mohanlal Sukhadia University (MLSU), Udaipur',
      targetProgram: 'Ph.D',
      specialization: 'Tribal Micro-finance & Livelihoods',
      ugcNetRollNo: 'RJ01004120',
      ugcNetScore: 64.0,
      ugcNetYear: '2024',
      isJrfQualified: false,
    },
    bankDetails: {
      accountHolderName: 'Rajeshwari Bhil',
      accountNumber: '61029104910',
      ifscCode: 'SBIN0031201',
      bankName: 'State Bank of India',
      branchName: 'Banswara Main',
      isAadhaarSeeded: true,
    },
    documents: [
      {
        id: 'doc_45_marks',
        type: 'marksheet',
        name: 'MA_Economics_Marksheet.pdf',
        size: 1500000,
        uploadedAt: '2026-02-06T15:25:00Z',
        ocrStatus: 'mismatch',
        ocrConfidence: 45,
        mismatches: [
          'Qualifying percentage (53.5%) is 1.5% below mandatory 55.0% MoTA statutory cutoff',
        ],
        extractedFields: {
          'Aggregate Percentage': '53.5%',
        },
      },
    ],
    aiAnalysis: {
      overallConfidence: 45,
      eligibilityPassed: false,
      requiresHumanReview: true,
      flags: [
        'Qualifying percentage (53.5%) is borderline below 55.0% cutoff (-35% confidence)',
        'UGC-NET scorecard not backed by JRF award (-15% confidence)',
      ],
      riskScore: 'Medium',
      meritScore: 48,
      verifiedFieldsCount: 8,
      totalFieldsCount: 16,
      summary: 'Borderline cutoff deficit (45% confidence). Scored 53.5% vs statutory 55% requirement. Flagged for committee review.',
    },
    deficiencies: [
      {
        id: 'def_45_cutoff',
        field: 'qualifyingPercentage',
        title: 'Qualifying Score Below Scheme Cutoff',
        description: 'Candidate scored 53.5%, which is 1.5% below statutory 55.0% cutoff for ST candidates.',
        severity: 'critical',
        issuedAt: '2026-02-06T15:30:00Z',
        isResolved: false,
      },
    ],
  },
];

// Curated Cohort: 100% Flawless & Fully Verified Candidate
export const COHORT_100PCT_FLAWLESS: Application[] = [
  COHORT_20PCT_CONFIDENCE_SPECTRUM[0], // Ananya Soren - 100% verified, 100% confidence
];

// Curated Cohort: Ineligible Candidate Who Fails Statutory Cutoff (Cannot Submit Application)
export const COHORT_INELIGIBLE_NO_MARKS: Application[] = [
  {
    id: 'app_ineligible_001',
    applicationNumber: 'NFST/2026/INELIGIBLE-MARKS',
    scheme: 'NFST',
    submittedAt: '2026-02-07T11:20:00Z',
    updatedAt: '2026-02-07T11:20:00Z',
    status: 'rejected',
    applicant: {
      fullName: 'Ramesh Kumar Munda',
      fatherName: 'Mangal Munda',
      motherName: 'Jasmani Munda',
      gender: 'Male',
      dob: '2001-03-10',
      aadhaarNumber: 'XXXX-XXXX-9142',
      mobile: '+91 94311 88219',
      email: 'ramesh.munda.ineligible@gmail.com',
      stCommunity: 'Munda',
      state: 'Jharkhand',
      district: 'Ranchi',
      pincode: '834001',
      domicileState: 'Jharkhand',
      annualFamilyIncome: 180000,
      parentOccupation: 'Cultivator',
    },
    academic: {
      qualifyingDegree: 'Bachelor of Arts (Pass Course)',
      qualifyingPercentage: 38.0,
      passingYear: 2024,
      institutionName: 'St. Xavier College, Ranchi',
      targetProgram: 'Ph.D',
      specialization: 'Tribal Regional History',
      ugcNetRollNo: 'JH02008819',
      ugcNetScore: 22.0,
      ugcNetYear: '2024',
      isJrfQualified: false,
    },
    bankDetails: {
      accountHolderName: 'Ramesh Kumar Munda',
      accountNumber: '38192019482',
      ifscCode: 'SBIN0000167',
      bankName: 'State Bank of India',
      branchName: 'Ranchi Main Branch',
      isAadhaarSeeded: true,
    },
    documents: [
      {
        id: 'doc_inel_caste',
        type: 'caste_certificate',
        name: 'ST_Certificate_Ramesh_Munda.pdf',
        size: 980000,
        uploadedAt: '2026-02-07T11:25:00Z',
        ocrStatus: 'verified',
        ocrConfidence: 95,
        extractedFields: {
          'Candidate Name': 'Ramesh Kumar Munda',
          'Community': 'Munda (Scheduled Tribe)',
          'Issuing Authority': 'Tahsildar, Ranchi',
        },
      },
      {
        id: 'doc_inel_marks',
        type: 'marksheet',
        name: 'BA_Consolidated_Marksheet_38pct.pdf',
        size: 1120000,
        uploadedAt: '2026-02-07T11:27:00Z',
        ocrStatus: 'mismatch',
        ocrConfidence: 20,
        mismatches: [
          'Qualifying aggregate of 38.0% is 17.0% below the mandatory MoTA 55.0% statutory cutoff for ST applicants.',
          'Statutory Prohibition: Candidates below 55% aggregate cannot submit an application under MoTA statutory guidelines.',
        ],
        extractedFields: {
          'Aggregate Percentage': '38.0%',
          'Result': 'Third Division (Fails Statutory Cutoff)',
        },
      },
    ],
    aiAnalysis: {
      overallConfidence: 20,
      eligibilityPassed: false,
      requiresHumanReview: true,
      flags: [
        'Statutorily Ineligible: Qualifying aggregate of 38.0% fails mandatory 55.0% MoTA statutory cutoff',
        'Submission Prohibited: Under MoTA statutory guidelines, candidate does not meet minimum marks criteria',
      ],
      riskScore: 'High',
      meritScore: 20,
      verifiedFieldsCount: 2,
      totalFieldsCount: 16,
      summary: 'Statutorily Ineligible. Scored 38.0%, which is 17% below the mandatory MoTA 55.0% cutoff. Application submission is prohibited by statutory guidelines.',
    },
    deficiencies: [
      {
        id: 'def_inel_marks',
        field: 'qualifyingPercentage',
        title: 'Qualifying Score Below Scheme Cutoff',
        description: 'Candidate scored 38.0%, which is below the mandatory MoTA 55.0% statutory cutoff. Prohibited from submitting application.',
        severity: 'critical',
        issuedAt: '2026-02-07T11:30:00Z',
        isResolved: false,
      },
    ],
  },
];

// Curated Cohort: Wrong and Fraudulent Documents Detected (Severe Mismatches - 18% Confidence)
export const COHORT_FRAUD_WRONG_DOCUMENTS: Application[] = [
  {
    id: 'app_fraud_001',
    applicationNumber: 'NFST/2026/FRAUD-WRONGDOCS',
    scheme: 'NFST',
    submittedAt: '2026-02-08T16:00:00Z',
    updatedAt: '2026-02-08T16:00:00Z',
    status: 'flagged_deficiency',
    applicant: {
      fullName: 'Deepak Verma',
      fatherName: 'Surendra Verma',
      motherName: 'Kamla Verma',
      gender: 'Male',
      dob: '1998-05-20',
      aadhaarNumber: 'XXXX-XXXX-3829',
      mobile: '+91 98210 49182',
      email: 'deepak.verma.suspicious@gmail.com',
      stCommunity: 'Kurmi (Claimed ST)',
      state: 'Jharkhand',
      district: 'Bokaro',
      pincode: '827001',
      domicileState: 'Jharkhand',
      annualFamilyIncome: 1450000,
      parentOccupation: 'Contractor',
    },
    academic: {
      qualifyingDegree: 'Bachelor of Technology (General)',
      qualifyingPercentage: 42.0,
      passingYear: 2022,
      institutionName: 'Private Engineering Institute',
      targetProgram: 'Ph.D',
      specialization: 'Information Technology',
      ugcNetRollNo: 'JH01009921',
      ugcNetScore: 31.0,
      ugcNetYear: '2023',
      isJrfQualified: false,
    },
    bankDetails: {
      accountHolderName: 'Deepak Verma',
      accountNumber: '19201948192',
      ifscCode: 'SBIN0000491',
      bankName: 'State Bank of India',
      branchName: 'Bokaro Steel City',
      isAadhaarSeeded: false,
    },
    documents: [
      {
        id: 'doc_fraud_power_bill',
        type: 'caste_certificate',
        name: 'Electricity_Utility_Power_Bill.pdf',
        size: 890000,
        uploadedAt: '2026-02-08T16:05:00Z',
        ocrStatus: 'mismatch',
        ocrConfidence: 15,
        mismatches: [
          'Wrong Document Slot: Uploaded file is an Electricity Consumer Bill, NOT a valid Scheduled Tribe Certificate.',
          'Consumer Name records "SURENDRA VERMA" (Category: Commercial LT Supply).',
          'Community Mismatch: No tribal certification found. Candidate belongs to OBC/General.',
        ],
        extractedFields: {
          'Document Type Detected': 'Utility Bill / Commercial Power Invoice',
          'Consumer Account No': '1092837482',
          'Bill Month': 'January 2026',
          'Amount Payable': 'Rs. 4,820.00',
        },
      },
      {
        id: 'doc_fraud_income_salary',
        type: 'income_certificate',
        name: 'Private_Contractor_Salary_Slip.pdf',
        size: 1040000,
        uploadedAt: '2026-02-08T16:07:00Z',
        ocrStatus: 'mismatch',
        ocrConfidence: 18,
        mismatches: [
          'Unauthorized Format: Uploaded document is a private pay-slip with an unverified revenue stamp.',
          'Annual Family Income of ₹14,50,000 exceeds statutory MoTA income limit of ₹8,00,000.',
        ],
        extractedFields: {
          'Annual Income Computed': '₹14,50,000',
          'Issuing Authority': 'Self-Declared / Forged Tahsildar Stamp',
        },
      },
      {
        id: 'doc_fraud_marks',
        type: 'marksheet',
        name: 'BTech_Low_Marksheet.pdf',
        size: 1200000,
        uploadedAt: '2026-02-08T16:09:00Z',
        ocrStatus: 'mismatch',
        ocrConfidence: 20,
        mismatches: [
          'Qualifying percentage (42.0%) fails mandatory MoTA 55.0% statutory cutoff.',
        ],
        extractedFields: {
          'Aggregate Percentage': '42.0%',
          'Division': 'Third Division',
        },
      },
    ],
    aiAnalysis: {
      overallConfidence: 18,
      eligibilityPassed: false,
      requiresHumanReview: true,
      flags: [
        'CRITICAL RED-FLAG: Wrong document slot detected (Commercial power bill uploaded as caste certificate)',
        'Unauthorized income pay-slip with unverified revenue seal exceeding income ceiling',
        'Academic aggregate below statutory cutoff (42.0% < 55.0%)',
        'Severe Integrity Risk: Case escalated to District Welfare Officer for physical inquiry',
      ],
      riskScore: 'High',
      meritScore: 15,
      verifiedFieldsCount: 1,
      totalFieldsCount: 16,
      summary: 'Severe Fraud & Integrity Risk: Wrong documents detected. Commercial electricity power bill uploaded for caste certificate, income exceeds statutory ceiling by ₹6.5L, and marks fail statutory cutoff. Confidence reduced to 18%.',
    },
    deficiencies: [
      {
        id: 'def_fraud_wrong_doc',
        field: 'caste_certificate',
        title: 'Wrong Document Uploaded for Caste Certificate',
        description: 'Uploaded document is a commercial electricity power bill, not a Scheduled Tribe caste certificate. Legal verification failed.',
        severity: 'critical',
        issuedAt: '2026-02-08T16:15:00Z',
        isResolved: false,
      },
      {
        id: 'def_fraud_income',
        field: 'annualFamilyIncome',
        title: 'Income Ceiling Exceeded & Unverified Stamp',
        description: 'Annual family income of ₹14.5 Lakhs exceeds MoTA statutory limit of ₹8.0 Lakhs.',
        severity: 'critical',
        issuedAt: '2026-02-08T16:15:00Z',
        isResolved: false,
      },
    ],
  },
];

// 2. Curated Cohort A: National Saturation Cohort (6 applications across 6 states)
export const COHORT_NATIONAL_SATURATION: Application[] = [
  ...SEEDED_APPLICATIONS,
];

// 3. Curated Cohort B: PVTG Fast-Track (Particularly Vulnerable Tribal Groups)
export const COHORT_PVTG_SCHOLARS: Application[] = [
  {
    id: 'app_pvtg_001',
    applicationNumber: 'NFST/2026/PVTG-01',
    scheme: 'NFST',
    submittedAt: '2026-01-14T09:30:00Z',
    updatedAt: '2026-01-14T09:30:00Z',
    status: 'submitted',
    applicant: {
      fullName: 'Lingamaiah Chenchu',
      fatherName: 'Guruvaiah Chenchu',
      motherName: 'Venkatamma Chenchu',
      gender: 'Male',
      dob: '1997-05-14',
      aadhaarNumber: 'XXXX-XXXX-7123',
      mobile: '+91 94401 23456',
      email: 'lingamaiah.chenchu@anu.edu.in',
      stCommunity: 'Chenchu (PVTG)',
      state: 'Andhra Pradesh',
      district: 'Prakasam (Nallamala)',
      pincode: '523315',
      domicileState: 'Andhra Pradesh',
      annualFamilyIncome: 180000,
      parentOccupation: 'Minor Forest Produce Collector',
    },
    academic: {
      qualifyingDegree: 'M.Sc. in Botany',
      qualifyingPercentage: 73.2,
      passingYear: 2024,
      institutionName: 'Acharya Nagarjuna University, Guntur',
      targetProgram: 'Ph.D',
      specialization: 'Medicinal Flora of Nallamala Forest',
      researchTopic: 'Ethnobotanical documentation of rare medicinal plants used by Chenchu PVTG elders',
      ugcNetRollNo: 'AP01004921',
      ugcNetScore: 92.5,
      ugcNetYear: '2024',
      isJrfQualified: true,
    },
    bankDetails: {
      accountHolderName: 'Lingamaiah Chenchu',
      accountNumber: '49102910492',
      ifscCode: 'SBIN0002781',
      bankName: 'State Bank of India',
      branchName: 'Dornala Tribal Branch',
      isAadhaarSeeded: true,
    },
    documents: [],
    aiAnalysis: {
      overallConfidence: 96,
      eligibilityPassed: true,
      requiresHumanReview: false,
      flags: ['Affirmative Priority: Particularly Vulnerable Tribal Group (PVTG)'],
      riskScore: 'Low',
      meritScore: 94,
      verifiedFieldsCount: 16,
      totalFieldsCount: 16,
      summary: 'Verified PVTG candidate with high research relevance to indigenous botanical conservation.',
    },
    deficiencies: [],
  },
  {
    id: 'app_pvtg_002',
    applicationNumber: 'NFST/2026/PVTG-02',
    scheme: 'NFST',
    submittedAt: '2026-01-15T11:00:00Z',
    updatedAt: '2026-01-15T11:00:00Z',
    status: 'submitted',
    applicant: {
      fullName: 'Devika Gond',
      fatherName: 'Shambhu Gond',
      motherName: 'Kamla Gond',
      gender: 'Female',
      dob: '1998-10-21',
      aadhaarNumber: 'XXXX-XXXX-9932',
      mobile: '+91 97551 88412',
      email: 'devika.gond@bhu.ac.in',
      stCommunity: 'Gond',
      state: 'Madhya Pradesh',
      district: 'Dindori',
      pincode: '481880',
      domicileState: 'Madhya Pradesh',
      annualFamilyIncome: 240000,
      parentOccupation: 'Gond Art Artisan & Agriculture',
    },
    academic: {
      qualifyingDegree: 'M.A. in Indigenous History',
      qualifyingPercentage: 76.8,
      passingYear: 2024,
      institutionName: 'Banaras Hindu University (BHU)',
      targetProgram: 'Ph.D',
      specialization: 'Central Indian Tribal Rebellions & Oral Epics',
      researchTopic: 'Preservation of oral narrative traditions among Gond tribal bards (Pradhans)',
      ugcNetRollNo: 'MP03001844',
      ugcNetScore: 96.2,
      ugcNetYear: '2024',
      isJrfQualified: true,
    },
    bankDetails: {
      accountHolderName: 'Devika Gond',
      accountNumber: '58192019482',
      ifscCode: 'UBIN0531201',
      bankName: 'Union Bank of India',
      branchName: 'Dindori Branch',
      isAadhaarSeeded: true,
    },
    documents: [],
    aiAnalysis: {
      overallConfidence: 97,
      eligibilityPassed: true,
      requiresHumanReview: false,
      flags: ['Affirmative Priority: Female ST Researcher in Humanities'],
      riskScore: 'Low',
      meritScore: 95,
      verifiedFieldsCount: 16,
      totalFieldsCount: 16,
      summary: 'Distinguished female researcher in indigenous oral history. High UGC-NET score (96.2%).',
    },
    deficiencies: [],
  },
  {
    id: 'app_pvtg_003',
    applicationNumber: 'NFST/2026/PVTG-03',
    scheme: 'NFST',
    submittedAt: '2026-01-16T14:20:00Z',
    updatedAt: '2026-01-16T14:20:00Z',
    status: 'submitted',
    applicant: {
      fullName: 'Budhan Birhor',
      fatherName: 'Mangal Birhor',
      motherName: 'Champa Birhor',
      gender: 'Male',
      dob: '1999-02-18',
      aadhaarNumber: 'XXXX-XXXX-1982',
      mobile: '+91 93341 55219',
      email: 'budhan.birhor@cuj.ac.in',
      stCommunity: 'Birhor (PVTG)',
      state: 'Jharkhand',
      district: 'Khunti (Birsa Munda Land)',
      pincode: '835210',
      domicileState: 'Jharkhand',
      annualFamilyIncome: 140000,
      parentOccupation: 'Rope Making & Traditional Foraging',
    },
    academic: {
      qualifyingDegree: 'M.Sc. in Forestry & Wildlife',
      qualifyingPercentage: 71.5,
      passingYear: 2025,
      institutionName: 'Central University of Jharkhand',
      targetProgram: 'Ph.D',
      specialization: 'Canopy Ecology & Indigenous Forest Practices',
      researchTopic: 'Birhor traditional rope weaving using Bauhinia vahlii creeper and sustainability',
      ugcNetRollNo: 'JH02008129',
      ugcNetScore: 89.4,
      ugcNetYear: '2025',
      isJrfQualified: true,
    },
    bankDetails: {
      accountHolderName: 'Budhan Birhor',
      accountNumber: '61029104829',
      ifscCode: 'SBIN0001829',
      bankName: 'State Bank of India',
      branchName: 'Khunti Bazar Branch',
      isAadhaarSeeded: true,
    },
    documents: [],
    aiAnalysis: {
      overallConfidence: 95,
      eligibilityPassed: true,
      requiresHumanReview: false,
      flags: ['Affirmative Priority: Particularly Vulnerable Tribal Group (PVTG)'],
      riskScore: 'Low',
      meritScore: 91,
      verifiedFieldsCount: 16,
      totalFieldsCount: 16,
      summary: 'First-generation scholar from Birhor nomadic community. High ecological value research.',
    },
    deficiencies: [],
  },
  {
    id: 'app_pvtg_004',
    applicationNumber: 'NOS/2026/PVTG-04',
    scheme: 'NOS',
    submittedAt: '2026-01-17T16:45:00Z',
    updatedAt: '2026-01-17T16:45:00Z',
    status: 'submitted',
    applicant: {
      fullName: 'Subarna Kondh',
      fatherName: 'Dambarudhar Kondh',
      motherName: 'Malati Kondh',
      gender: 'Female',
      dob: '1997-08-04',
      aadhaarNumber: 'XXXX-XXXX-6192',
      mobile: '+91 94371 44102',
      email: 'subarna.kondh@oxford.alumni.org',
      stCommunity: 'Dongria Kondh (PVTG)',
      state: 'Odisha',
      district: 'Rayagada',
      pincode: '765001',
      domicileState: 'Odisha',
      annualFamilyIncome: 210000,
      parentOccupation: 'Horticulture in Niyamgiri Hills',
    },
    academic: {
      qualifyingDegree: 'M.Sc. in Sustainable Development',
      qualifyingPercentage: 81.4,
      passingYear: 2024,
      institutionName: 'Ravenshaw University, Cuttack',
      targetProgram: 'Ph.D',
      specialization: 'Indigenous Agroforestry Systems',
      researchTopic: 'Traditional agricultural biodiversity of Niyamgiri hills',
      foreignUniversityName: 'University of Oxford, United Kingdom',
      qsWorldRanking: 3,
    },
    bankDetails: {
      accountHolderName: 'Subarna Kondh',
      accountNumber: '29104819201',
      ifscCode: 'SBIN0000167',
      bankName: 'State Bank of India',
      branchName: 'Rayagada Main',
      isAadhaarSeeded: true,
    },
    documents: [],
    aiAnalysis: {
      overallConfidence: 98,
      eligibilityPassed: true,
      requiresHumanReview: false,
      flags: ['Affirmative Priority: Dongria Kondh PVTG', 'Prestigious QS Top 10 Admission'],
      riskScore: 'Low',
      meritScore: 98,
      verifiedFieldsCount: 16,
      totalFieldsCount: 16,
      summary: 'Exceptional Dongria Kondh female scholar holding unconditional Ph.D offer at University of Oxford (QS #3).',
    },
    deficiencies: [],
  },
];

// 4. Curated Cohort C: Northeast Himalayan ST Scholars (Nagaland, Mizoram, Arunachal Pradesh, Sikkim)
export const COHORT_NORTHEAST_SCHOLARS: Application[] = [
  {
    id: 'app_ne_001',
    applicationNumber: 'NFST/2026/NE-01',
    scheme: 'NFST',
    submittedAt: '2026-02-01T10:15:00Z',
    updatedAt: '2026-02-01T10:15:00Z',
    status: 'submitted',
    applicant: {
      fullName: 'Temjenrenla Ao',
      fatherName: 'Imnamerang Ao',
      motherName: 'Alemlemla Ao',
      gender: 'Female',
      dob: '1998-03-12',
      aadhaarNumber: 'XXXX-XXXX-4421',
      mobile: '+91 94360 88219',
      email: 'temjenrenla.ao@nagalanduniv.ac.in',
      stCommunity: 'Ao',
      state: 'Nagaland',
      district: 'Mokokchung',
      pincode: '798601',
      domicileState: 'Nagaland',
      annualFamilyIncome: 380000,
      parentOccupation: 'Education & Organic Farming',
    },
    academic: {
      qualifyingDegree: 'M.A. in Linguistics & Folkloristics',
      qualifyingPercentage: 78.5,
      passingYear: 2024,
      institutionName: 'Nagaland University, Lumami',
      targetProgram: 'Ph.D',
      specialization: 'Tibeto-Burman Endangered Languages',
      researchTopic: 'Acoustic phonetic documentation of endangered Mongsen Ao dialects',
      ugcNetRollNo: 'NL01002918',
      ugcNetScore: 97.1,
      ugcNetYear: '2024',
      isJrfQualified: true,
    },
    bankDetails: {
      accountHolderName: 'Temjenrenla Ao',
      accountNumber: '31092849102',
      ifscCode: 'SBIN0000137',
      bankName: 'State Bank of India',
      branchName: 'Mokokchung Main',
      isAadhaarSeeded: true,
    },
    documents: [],
    aiAnalysis: {
      overallConfidence: 97,
      eligibilityPassed: true,
      requiresHumanReview: false,
      flags: ['Affirmative Priority: North-East Female ST Scholar'],
      riskScore: 'Low',
      meritScore: 96,
      verifiedFieldsCount: 16,
      totalFieldsCount: 16,
      summary: 'Outstanding Ao Naga female linguist documenting critically endangered oral dialects.',
    },
    deficiencies: [],
  },
  {
    id: 'app_ne_002',
    applicationNumber: 'NOS/2026/NE-02',
    scheme: 'NOS',
    submittedAt: '2026-02-02T12:30:00Z',
    updatedAt: '2026-02-02T12:30:00Z',
    status: 'submitted',
    applicant: {
      fullName: 'Lalremruata Sailo',
      fatherName: 'C. Lalbiakzuala',
      motherName: 'Lalnunfeli Sailo',
      gender: 'Male',
      dob: '1997-11-25',
      aadhaarNumber: 'XXXX-XXXX-9102',
      mobile: '+91 94361 77123',
      email: 'lalremruata.sailo@mzu.edu.in',
      stCommunity: 'Mizo',
      state: 'Mizoram',
      district: 'Aizawl',
      pincode: '796004',
      domicileState: 'Mizoram',
      annualFamilyIncome: 420000,
      parentOccupation: 'Horticulture Department',
    },
    academic: {
      qualifyingDegree: 'M.Tech in Earthquake Geotechnical Engineering',
      qualifyingPercentage: 82.3,
      passingYear: 2024,
      institutionName: 'Mizoram University (MZU)',
      targetProgram: 'Ph.D',
      specialization: 'Seismic Hazards in Himalayan Fold Belts',
      foreignUniversityName: 'Imperial College London, United Kingdom',
      qsWorldRanking: 6,
    },
    bankDetails: {
      accountHolderName: 'Lalremruata Sailo',
      accountNumber: '48192019481',
      ifscCode: 'SBIN0001539',
      bankName: 'State Bank of India',
      branchName: 'Aizawl Main Branch',
      isAadhaarSeeded: true,
    },
    documents: [],
    aiAnalysis: {
      overallConfidence: 98,
      eligibilityPassed: true,
      requiresHumanReview: false,
      flags: ['QS Top 10 Offer', 'Critical Seismic Research for Himalayan Infrastructure'],
      riskScore: 'Low',
      meritScore: 97,
      verifiedFieldsCount: 16,
      totalFieldsCount: 16,
      summary: 'High-merit Mizo scholar holding unconditional Ph.D offer at Imperial College London (QS #6).',
    },
    deficiencies: [],
  },
  {
    id: 'app_ne_003',
    applicationNumber: 'NFST/2026/NE-03',
    scheme: 'NFST',
    submittedAt: '2026-02-03T14:00:00Z',
    updatedAt: '2026-02-03T14:00:00Z',
    status: 'submitted',
    applicant: {
      fullName: 'Tashi Wangdi Monpa',
      fatherName: 'Dorjee Monpa',
      motherName: 'Karma Monpa',
      gender: 'Male',
      dob: '1998-06-19',
      aadhaarNumber: 'XXXX-XXXX-3829',
      mobile: '+91 94362 11928',
      email: 'tashi.monpa@rgu.ac.in',
      stCommunity: 'Monpa',
      state: 'Arunachal Pradesh',
      district: 'Tawang',
      pincode: '790104',
      domicileState: 'Arunachal Pradesh',
      annualFamilyIncome: 290000,
      parentOccupation: 'High Altitude Agro-Pastoralism',
    },
    academic: {
      qualifyingDegree: 'M.Sc. in Glaciology & Himalayan Studies',
      qualifyingPercentage: 74.8,
      passingYear: 2024,
      institutionName: 'Rajiv Gandhi University (RGU), Doimukh',
      targetProgram: 'Ph.D',
      specialization: 'Glacial Lake Outburst Floods (GLOF) Early Warning',
      researchTopic: 'Cryospheric dynamics of Eastern Himalayan glaciers in Tawang and West Kameng',
      ugcNetRollNo: 'AR01001829',
      ugcNetScore: 93.6,
      ugcNetYear: '2024',
      isJrfQualified: true,
    },
    bankDetails: {
      accountHolderName: 'Tashi Wangdi Monpa',
      accountNumber: '29104928192',
      ifscCode: 'SBIN0005844',
      bankName: 'State Bank of India',
      branchName: 'Tawang Branch',
      isAadhaarSeeded: true,
    },
    documents: [],
    aiAnalysis: {
      overallConfidence: 96,
      eligibilityPassed: true,
      requiresHumanReview: false,
      flags: ['Border District Priority: Tawang', 'High Climate Relevance'],
      riskScore: 'Low',
      meritScore: 93,
      verifiedFieldsCount: 16,
      totalFieldsCount: 16,
      summary: 'Monpa scholar from border high-altitude region conducting vital Himalayan cryosphere studies.',
    },
    deficiencies: [],
  },
  {
    id: 'app_ne_004',
    applicationNumber: 'NFST/2026/NE-04',
    scheme: 'NFST',
    submittedAt: '2026-02-04T15:10:00Z',
    updatedAt: '2026-02-04T15:10:00Z',
    status: 'submitted',
    applicant: {
      fullName: 'Diki Ongmu Bhutia',
      fatherName: 'Sonam Bhutia',
      motherName: 'Pema Bhutia',
      gender: 'Female',
      dob: '1999-01-28',
      aadhaarNumber: 'XXXX-XXXX-8271',
      mobile: '+91 94340 33918',
      email: 'diki.bhutia@cus.ac.in',
      stCommunity: 'Bhutia',
      state: 'Sikkim',
      district: 'Mangan (North Sikkim)',
      pincode: '737116',
      domicileState: 'Sikkim',
      annualFamilyIncome: 350000,
      parentOccupation: 'Cardamom Cultivator',
    },
    academic: {
      qualifyingDegree: 'M.Sc. in Microbiology',
      qualifyingPercentage: 77.2,
      passingYear: 2025,
      institutionName: 'Sikkim University, Gangtok',
      targetProgram: 'Ph.D',
      specialization: 'Microbial Ecology of Traditional Fermented Foods',
      researchTopic: 'Metagenomic analysis of Kinema and Chhurpi traditional fermented bio-products',
      ugcNetRollNo: 'SK01004819',
      ugcNetScore: 95.8,
      ugcNetYear: '2025',
      isJrfQualified: true,
    },
    bankDetails: {
      accountHolderName: 'Diki Ongmu Bhutia',
      accountNumber: '39102948192',
      ifscCode: 'SBIN0000232',
      bankName: 'State Bank of India',
      branchName: 'Gangtok Main',
      isAadhaarSeeded: true,
    },
    documents: [],
    aiAnalysis: {
      overallConfidence: 97,
      eligibilityPassed: true,
      requiresHumanReview: false,
      flags: ['Affirmative Priority: Female ST Himalayan Scholar'],
      riskScore: 'Low',
      meritScore: 95,
      verifiedFieldsCount: 16,
      totalFieldsCount: 16,
      summary: 'Distinguished Bhutia female microbiologist studying indigenous Himalayan biotechnology.',
    },
    deficiencies: [],
  },
];

// 5. Curated Cohort D: Western Belt Forest Corridor (Rajasthan, Gujarat, Maharashtra)
export const COHORT_WESTERN_BELT_SCHOLARS: Application[] = [
  {
    id: 'app_west_001',
    applicationNumber: 'NFST/2026/WB-01',
    scheme: 'NFST',
    submittedAt: '2026-02-10T10:00:00Z',
    updatedAt: '2026-02-10T10:00:00Z',
    status: 'submitted',
    applicant: {
      fullName: 'Sunita Meena',
      fatherName: 'Ramkishan Meena',
      motherName: 'Kamla Devi Meena',
      gender: 'Female',
      dob: '1998-07-15',
      aadhaarNumber: 'XXXX-XXXX-5512',
      mobile: '+91 94140 66291',
      email: 'sunita.meena@uniraj.ac.in',
      stCommunity: 'Meena',
      state: 'Rajasthan',
      district: 'Banswara',
      pincode: '327001',
      domicileState: 'Rajasthan',
      annualFamilyIncome: 310000,
      parentOccupation: 'Agriculture & Livestock',
    },
    academic: {
      qualifyingDegree: 'M.Sc. in Renewable Energy Systems',
      qualifyingPercentage: 79.1,
      passingYear: 2024,
      institutionName: 'University of Rajasthan, Jaipur',
      targetProgram: 'Ph.D',
      specialization: 'Decentralized Solar Microgrids for Tribal Hamlets',
      researchTopic: 'Techno-economic feasibility of community solar storage in southern Rajasthan tribal belt',
      ugcNetRollNo: 'RJ01008491',
      ugcNetScore: 96.4,
      ugcNetYear: '2024',
      isJrfQualified: true,
    },
    bankDetails: {
      accountHolderName: 'Sunita Meena',
      accountNumber: '58192039182',
      ifscCode: 'SBIN0001524',
      bankName: 'State Bank of India',
      branchName: 'Banswara Main',
      isAadhaarSeeded: true,
    },
    documents: [],
    aiAnalysis: {
      overallConfidence: 97,
      eligibilityPassed: true,
      requiresHumanReview: false,
      flags: ['Female ST Scholar in Clean Tech'],
      riskScore: 'Low',
      meritScore: 96,
      verifiedFieldsCount: 16,
      totalFieldsCount: 16,
      summary: 'High-achieving female engineering scholar focusing on rural tribal solar energy transition.',
    },
    deficiencies: [],
  },
  {
    id: 'app_west_002',
    applicationNumber: 'NFST/2026/WB-02',
    scheme: 'NFST',
    submittedAt: '2026-02-11T11:20:00Z',
    updatedAt: '2026-02-11T11:20:00Z',
    status: 'submitted',
    applicant: {
      fullName: 'Jignesh Rathawa',
      fatherName: 'Pravin Rathawa',
      motherName: 'Narmadaben Rathawa',
      gender: 'Male',
      dob: '1999-04-03',
      aadhaarNumber: 'XXXX-XXXX-9912',
      mobile: '+91 98250 44192',
      email: 'jignesh.rathawa@msubaroda.ac.in',
      stCommunity: 'Rathawa',
      state: 'Gujarat',
      district: 'Chhota Udaipur',
      pincode: '391165',
      domicileState: 'Gujarat',
      annualFamilyIncome: 220000,
      parentOccupation: 'Pithora Tribal Art Painting & Agriculture',
    },
    academic: {
      qualifyingDegree: 'Master of Visual Arts (MVA)',
      qualifyingPercentage: 75.6,
      passingYear: 2024,
      institutionName: 'MS University of Baroda',
      targetProgram: 'Ph.D',
      specialization: 'Indigenous Visual Semiotics & Sacred Murals',
      researchTopic: 'Ritual iconography of Pithora sacred wall murals and heritage digitization',
      ugcNetRollNo: 'GJ02004819',
      ugcNetScore: 94.2,
      ugcNetYear: '2024',
      isJrfQualified: true,
    },
    bankDetails: {
      accountHolderName: 'Jignesh Rathawa',
      accountNumber: '48192019481',
      ifscCode: 'BARB0CHHOTA',
      bankName: 'Bank of Baroda',
      branchName: 'Chhota Udaipur Branch',
      isAadhaarSeeded: true,
    },
    documents: [],
    aiAnalysis: {
      overallConfidence: 96,
      eligibilityPassed: true,
      requiresHumanReview: false,
      flags: ['Master Pithora Tribal Artisan Scholar'],
      riskScore: 'Low',
      meritScore: 93,
      verifiedFieldsCount: 16,
      totalFieldsCount: 16,
      summary: 'Rathawa tribal artist scholar dedicated to preserving ancient Pithora sacred ritual art forms.',
    },
    deficiencies: [],
  },
  {
    id: 'app_west_003',
    applicationNumber: 'NOS/2026/WB-03',
    scheme: 'NOS',
    submittedAt: '2026-02-12T14:15:00Z',
    updatedAt: '2026-02-12T14:15:00Z',
    status: 'submitted',
    applicant: {
      fullName: 'Pratibha Warli',
      fatherName: 'Jivya Warli',
      motherName: 'Sitabai Warli',
      gender: 'Female',
      dob: '1997-09-11',
      aadhaarNumber: 'XXXX-XXXX-2019',
      mobile: '+91 98901 33201',
      email: 'pratibha.warli@tiss.edu',
      stCommunity: 'Warli',
      state: 'Maharashtra',
      district: 'Palghar',
      pincode: '401602',
      domicileState: 'Maharashtra',
      annualFamilyIncome: 280000,
      parentOccupation: 'Warli Art Artisan',
    },
    academic: {
      qualifyingDegree: 'M.A. in Social Anthropology',
      qualifyingPercentage: 80.2,
      passingYear: 2024,
      institutionName: 'Tata Institute of Social Sciences (TISS), Mumbai',
      targetProgram: 'Ph.D',
      specialization: 'Indigenous Ecology & Sacred Topography',
      foreignUniversityName: 'Australian National University (ANU), Australia',
      qsWorldRanking: 30,
    },
    bankDetails: {
      accountHolderName: 'Pratibha Warli',
      accountNumber: '59102948192',
      ifscCode: 'SBIN0000418',
      bankName: 'State Bank of India',
      branchName: 'Dahanu Road Branch',
      isAadhaarSeeded: true,
    },
    documents: [],
    aiAnalysis: {
      overallConfidence: 98,
      eligibilityPassed: true,
      requiresHumanReview: false,
      flags: ['Warli Female Scholar', 'Unconditional QS Top 50 Offer'],
      riskScore: 'Low',
      meritScore: 97,
      verifiedFieldsCount: 16,
      totalFieldsCount: 16,
      summary: 'Exceptional Warli indigenous researcher with unconditional admission at ANU Canberra (QS #30).',
    },
    deficiencies: [],
  },
];

// 6. Curated Cohort E: Southern Belt PVTG & Forest Tribes (Tamil Nadu, Kerala, Karnataka)
export const COHORT_SOUTHERN_BELT_SCHOLARS: Application[] = [
  {
    id: 'app_south_001',
    applicationNumber: 'NFST/2026/SB-01',
    scheme: 'NFST',
    submittedAt: '2026-02-15T09:40:00Z',
    updatedAt: '2026-02-15T09:40:00Z',
    status: 'submitted',
    applicant: {
      fullName: 'Sinivasan Toda',
      fatherName: 'Pillayar Toda',
      motherName: 'Ponni Toda',
      gender: 'Male',
      dob: '1998-05-22',
      aadhaarNumber: 'XXXX-XXXX-6612',
      mobile: '+91 94430 77192',
      email: 'sinivasan.toda@bharathiar.ac.in',
      stCommunity: 'Toda (PVTG)',
      state: 'Tamil Nadu',
      district: 'The Nilgiris (Ooty)',
      pincode: '643001',
      domicileState: 'Tamil Nadu',
      annualFamilyIncome: 190000,
      parentOccupation: 'Traditional Pastoral Buffalo Herder',
    },
    academic: {
      qualifyingDegree: 'M.Sc. in Environmental Sciences',
      qualifyingPercentage: 75.3,
      passingYear: 2024,
      institutionName: 'Bharathiar University, Coimbatore',
      targetProgram: 'Ph.D',
      specialization: 'Shola-Grassland High Altitude Ecology',
      researchTopic: 'Conservation ecology of Nilgiri Shola grasslands and Toda sacred groves',
      ugcNetRollNo: 'TN02003819',
      ugcNetScore: 94.7,
      ugcNetYear: '2024',
      isJrfQualified: true,
    },
    bankDetails: {
      accountHolderName: 'Sinivasan Toda',
      accountNumber: '48192019481',
      ifscCode: 'SBIN0000889',
      bankName: 'State Bank of India',
      branchName: 'Ooty Commercial Road',
      isAadhaarSeeded: true,
    },
    documents: [],
    aiAnalysis: {
      overallConfidence: 96,
      eligibilityPassed: true,
      requiresHumanReview: false,
      flags: ['Affirmative Priority: Toda PVTG Scholar'],
      riskScore: 'Low',
      meritScore: 94,
      verifiedFieldsCount: 16,
      totalFieldsCount: 16,
      summary: 'Toda PVTG scholar dedicated to conserving critical high-altitude Nilgiri Shola ecosystems.',
    },
    deficiencies: [],
  },
  {
    id: 'app_south_002',
    applicationNumber: 'NFST/2026/SB-02',
    scheme: 'NFST',
    submittedAt: '2026-02-16T11:00:00Z',
    updatedAt: '2026-02-16T11:00:00Z',
    status: 'submitted',
    applicant: {
      fullName: 'Amina Kurumba',
      fatherName: 'Ramanan Kurumba',
      motherName: 'Kamala Kurumba',
      gender: 'Female',
      dob: '1999-08-30',
      aadhaarNumber: 'XXXX-XXXX-1932',
      mobile: '+91 94471 22891',
      email: 'amina.kurumba@keralauniv.ac.in',
      stCommunity: 'Kurumba (PVTG)',
      state: 'Kerala',
      district: 'Palakkad (Attappadi)',
      pincode: '678581',
      domicileState: 'Kerala',
      annualFamilyIncome: 160000,
      parentOccupation: 'Attappadi Traditional Agro-Forestry',
    },
    academic: {
      qualifyingDegree: 'M.Sc. in Nutrition & Dietetics',
      qualifyingPercentage: 76.5,
      passingYear: 2024,
      institutionName: 'University of Kerala, Kariavattom',
      targetProgram: 'Ph.D',
      specialization: 'Indigenous Millets & Maternal Nutritional Health',
      researchTopic: 'Revitalizing traditional tribal millets (Ragi, Chama) for combating anemia in Attappadi hamlets',
      ugcNetRollNo: 'KL01004918',
      ugcNetScore: 95.1,
      ugcNetYear: '2024',
      isJrfQualified: true,
    },
    bankDetails: {
      accountHolderName: 'Amina Kurumba',
      accountNumber: '29104819201',
      ifscCode: 'SBIN0008620',
      bankName: 'State Bank of India',
      branchName: 'Agali Attappadi Branch',
      isAadhaarSeeded: true,
    },
    documents: [],
    aiAnalysis: {
      overallConfidence: 97,
      eligibilityPassed: true,
      requiresHumanReview: false,
      flags: ['Affirmative Priority: Kurumba PVTG Female Scholar'],
      riskScore: 'Low',
      meritScore: 95,
      verifiedFieldsCount: 16,
      totalFieldsCount: 16,
      summary: 'Kurumba PVTG female researcher pioneering indigenous tribal nutrition solutions in Attappadi.',
    },
    deficiencies: [],
  },
  {
    id: 'app_south_003',
    applicationNumber: 'NFST/2026/SB-03',
    scheme: 'NFST',
    submittedAt: '2026-02-17T13:30:00Z',
    updatedAt: '2026-02-17T13:30:00Z',
    status: 'submitted',
    applicant: {
      fullName: 'Basavaraj Jenu Kuruba',
      fatherName: 'Channappa Jenu Kuruba',
      motherName: 'Gowramma Jenu Kuruba',
      gender: 'Male',
      dob: '1998-12-05',
      aadhaarNumber: 'XXXX-XXXX-8821',
      mobile: '+91 94801 55291',
      email: 'basavaraj.kuruba@uni-mysore.ac.in',
      stCommunity: 'Jenu Kuruba (PVTG)',
      state: 'Karnataka',
      district: 'Mysuru (Hunsur)',
      pincode: '571105',
      domicileState: 'Karnataka',
      annualFamilyIncome: 175000,
      parentOccupation: 'Traditional Forest Honey Collector',
    },
    academic: {
      qualifyingDegree: 'M.Sc. in Entomology',
      qualifyingPercentage: 74.0,
      passingYear: 2024,
      institutionName: 'University of Mysore',
      targetProgram: 'Ph.D',
      specialization: 'Wild Apiculture & Pollinator Conservation',
      researchTopic: 'Apis dorsata giant rock bee nesting dynamics in Nagarahole tiger reserve canopy',
      ugcNetRollNo: 'KA03001928',
      ugcNetScore: 93.8,
      ugcNetYear: '2024',
      isJrfQualified: true,
    },
    bankDetails: {
      accountHolderName: 'Basavaraj Jenu Kuruba',
      accountNumber: '39102948192',
      ifscCode: 'SBIN0000845',
      bankName: 'State Bank of India',
      branchName: 'Hunsur Branch',
      isAadhaarSeeded: true,
    },
    documents: [],
    aiAnalysis: {
      overallConfidence: 96,
      eligibilityPassed: true,
      requiresHumanReview: false,
      flags: ['Affirmative Priority: Jenu Kuruba PVTG Scholar'],
      riskScore: 'Low',
      meritScore: 93,
      verifiedFieldsCount: 16,
      totalFieldsCount: 16,
      summary: 'Jenu Kuruba scholar applying generational traditional bee knowledge to wild pollinator conservation.',
    },
    deficiencies: [],
  },
];

// 7. Curated Cohort F: Northern Frontier & Himalayan STs (Ladakh, Jammu & Kashmir, Himachal, Uttarakhand)
export const COHORT_NORTHERN_HIMALAYAN_SCHOLARS: Application[] = [
  {
    id: 'app_north_001',
    applicationNumber: 'NFST/2026/NH-01',
    scheme: 'NFST',
    submittedAt: '2026-02-20T10:00:00Z',
    updatedAt: '2026-02-20T10:00:00Z',
    status: 'submitted',
    applicant: {
      fullName: 'Stanzin Dorje Changpa',
      fatherName: 'Tsering Changpa',
      motherName: 'Diskit Changpa',
      gender: 'Male',
      dob: '1998-04-18',
      aadhaarNumber: 'XXXX-XXXX-9912',
      mobile: '+91 94191 77281',
      email: 'stanzin.changpa@uol.ac.in',
      stCommunity: 'Changpa',
      state: 'Ladakh',
      district: 'Leh (Changthang)',
      pincode: '194101',
      domicileState: 'Ladakh',
      annualFamilyIncome: 240000,
      parentOccupation: 'Pashmina Goat Pastoralist',
    },
    academic: {
      qualifyingDegree: 'M.Sc. in High Altitude Animal Physiology',
      qualifyingPercentage: 75.8,
      passingYear: 2024,
      institutionName: 'University of Ladakh, Leh',
      targetProgram: 'Ph.D',
      specialization: 'Cold Desert Pastoral Adaptation & Pashmina Fiber Quality',
      researchTopic: 'Impact of climate change on winter forage and fiber yield in Changthang plateau',
      ugcNetRollNo: 'LA01001928',
      ugcNetScore: 94.6,
      ugcNetYear: '2024',
      isJrfQualified: true,
    },
    bankDetails: {
      accountHolderName: 'Stanzin Dorje Changpa',
      accountNumber: '48192019481',
      ifscCode: 'SBIN0001365',
      bankName: 'State Bank of India',
      branchName: 'Leh Main Branch',
      isAadhaarSeeded: true,
    },
    documents: [],
    aiAnalysis: {
      overallConfidence: 97,
      eligibilityPassed: true,
      requiresHumanReview: false,
      flags: ['High Altitude Ladakh Pastoralist Cohort'],
      riskScore: 'Low',
      meritScore: 94,
      verifiedFieldsCount: 16,
      totalFieldsCount: 16,
      summary: 'Changpa scholar from 14,000 ft Changthang high-altitude nomadic pastoral community.',
    },
    deficiencies: [],
  },
  {
    id: 'app_north_002',
    applicationNumber: 'NFST/2026/NH-02',
    scheme: 'NFST',
    submittedAt: '2026-02-21T11:45:00Z',
    updatedAt: '2026-02-21T11:45:00Z',
    status: 'submitted',
    applicant: {
      fullName: 'Farida Gujjar',
      fatherName: 'Choudhary Bashir Gujjar',
      motherName: 'Zainab Begum',
      gender: 'Female',
      dob: '1999-03-14',
      aadhaarNumber: 'XXXX-XXXX-4192',
      mobile: '+91 94190 44102',
      email: 'farida.gujjar@bgsbu.ac.in',
      stCommunity: 'Gujjar',
      state: 'Jammu and Kashmir',
      district: 'Rajouri',
      pincode: '185131',
      domicileState: 'Jammu and Kashmir',
      annualFamilyIncome: 210000,
      parentOccupation: 'Transhumant Pastoralism',
    },
    academic: {
      qualifyingDegree: 'M.A. in Rural Development & Economics',
      qualifyingPercentage: 78.2,
      passingYear: 2024,
      institutionName: 'BGSB University, Rajouri',
      targetProgram: 'Ph.D',
      specialization: 'Transhumant Tribal Migratory Routes & Education Access',
      researchTopic: 'Mobile seasonal schooling models for Gujjar-Bakarwal children during alpine migration',
      ugcNetRollNo: 'JK02008192',
      ugcNetScore: 96.0,
      ugcNetYear: '2024',
      isJrfQualified: true,
    },
    bankDetails: {
      accountHolderName: 'Farida Gujjar',
      accountNumber: '29104928192',
      ifscCode: 'JAKA0RAJOUR',
      bankName: 'Jammu and Kashmir Bank',
      branchName: 'Rajouri Main',
      isAadhaarSeeded: true,
    },
    documents: [],
    aiAnalysis: {
      overallConfidence: 97,
      eligibilityPassed: true,
      requiresHumanReview: false,
      flags: ['Affirmative Priority: Female Gujjar Scholar in J&K'],
      riskScore: 'Low',
      meritScore: 95,
      verifiedFieldsCount: 16,
      totalFieldsCount: 16,
      summary: 'Pioneering female Gujjar scholar advocating for seasonal pastoral educational policy.',
    },
    deficiencies: [],
  },
  {
    id: 'app_north_003',
    applicationNumber: 'NFST/2026/NH-03',
    scheme: 'NFST',
    submittedAt: '2026-02-22T14:10:00Z',
    updatedAt: '2026-02-22T14:10:00Z',
    status: 'submitted',
    applicant: {
      fullName: 'Vikram Gaddi',
      fatherName: 'Mansha Ram Gaddi',
      motherName: 'Kamla Devi Gaddi',
      gender: 'Male',
      dob: '1998-09-02',
      aadhaarNumber: 'XXXX-XXXX-7729',
      mobile: '+91 94180 55192',
      email: 'vikram.gaddi@hpuniv.ac.in',
      stCommunity: 'Gaddi',
      state: 'Himachal Pradesh',
      district: 'Chamba (Bharmour)',
      pincode: '176315',
      domicileState: 'Himachal Pradesh',
      annualFamilyIncome: 260000,
      parentOccupation: 'High Altitude Sheep & Goat Herder',
    },
    academic: {
      qualifyingDegree: 'M.Sc. in Botany & Mountain Ecology',
      qualifyingPercentage: 74.9,
      passingYear: 2024,
      institutionName: 'Himachal Pradesh University, Shimla',
      targetProgram: 'Ph.D',
      specialization: 'Alpine Pasture Ecology of Pir Panjal Range',
      researchTopic: 'Overgrazing dynamics vs climate shift in sub-alpine Bugyals of Bharmour tribal valley',
      ugcNetRollNo: 'HP01003819',
      ugcNetScore: 93.9,
      ugcNetYear: '2024',
      isJrfQualified: true,
    },
    bankDetails: {
      accountHolderName: 'Vikram Gaddi',
      accountNumber: '58192039182',
      ifscCode: 'SBIN0002319',
      bankName: 'State Bank of India',
      branchName: 'Bharmour Tribal Branch',
      isAadhaarSeeded: true,
    },
    documents: [],
    aiAnalysis: {
      overallConfidence: 96,
      eligibilityPassed: true,
      requiresHumanReview: false,
      flags: ['Bharmour ITDA Tribal Area Candidate'],
      riskScore: 'Low',
      meritScore: 93,
      verifiedFieldsCount: 16,
      totalFieldsCount: 16,
      summary: 'Gaddi mountain pastoralist researcher documenting sub-alpine alpine meadow ecology.',
    },
    deficiencies: [],
  },
  {
    id: 'app_north_004',
    applicationNumber: 'NOS/2026/NH-04',
    scheme: 'NOS',
    submittedAt: '2026-02-23T16:00:00Z',
    updatedAt: '2026-02-23T16:00:00Z',
    status: 'submitted',
    applicant: {
      fullName: 'Pooja Bhotia',
      fatherName: 'Dan Singh Bhotia',
      motherName: 'Parvati Bhotia',
      gender: 'Female',
      dob: '1997-12-14',
      aadhaarNumber: 'XXXX-XXXX-3310',
      mobile: '+91 94120 88192',
      email: 'pooja.bhotia@cam.ac.uk',
      stCommunity: 'Bhotia',
      state: 'Uttarakhand',
      district: 'Pithoragarh',
      pincode: '262545',
      domicileState: 'Uttarakhand',
      annualFamilyIncome: 340000,
      parentOccupation: 'Himalayan Herbal Collection & Weaving',
    },
    academic: {
      qualifyingDegree: 'M.Sc. in Pharmacology & Drug Discovery',
      qualifyingPercentage: 81.6,
      passingYear: 2024,
      institutionName: 'Kumaun University, Nainital',
      targetProgram: 'Ph.D',
      specialization: 'Bioactive Alkaloids from High-Altitude Alpine Flora',
      foreignUniversityName: 'University of Cambridge, United Kingdom',
      qsWorldRanking: 2,
    },
    bankDetails: {
      accountHolderName: 'Pooja Bhotia',
      accountNumber: '48192019481',
      ifscCode: 'SBIN0000698',
      bankName: 'State Bank of India',
      branchName: 'Pithoragarh Main',
      isAadhaarSeeded: true,
    },
    documents: [],
    aiAnalysis: {
      overallConfidence: 99,
      eligibilityPassed: true,
      requiresHumanReview: false,
      flags: ['QS Top 3 Cambridge Offer', 'Himalayan Pharmacology Specialist'],
      riskScore: 'Low',
      meritScore: 99,
      verifiedFieldsCount: 16,
      totalFieldsCount: 16,
      summary: 'Exceptional Bhotia female scholar with unconditional Ph.D offer at University of Cambridge (QS #2).',
    },
    deficiencies: [],
  },
];

// Curated Master Presets Available to Add One by One
export const PRESET_SCENARIOS: PresetScenario[] = [
  {
    id: 'preset_100pct_flawless',
    name: '100% Flawless Application (100% Verified Documents & Zero Defects)',
    badge: '100% Verified Pristine',
    badgeColor: 'bg-emerald-100 text-emerald-800 border-emerald-300',
    category: 'Pristine Verification Benchmark',
    description: '100% verified candidate (Ananya Soren). All documents verified with 100% character-by-character OCR match, digital e-Pramaan seals, zero discrepancies, zero flags, DBT active, and 100% confidence.',
    parameters: {
      incomeCeiling: 800000,
      marksThreshold: 55,
      totalSlots: 750,
      femaleQuota: 30,
    },
    additionalApplications: COHORT_100PCT_FLAWLESS,
    keyHighlights: [
      'Ananya Soren: 100% verified AI confidence & 100 merit index',
      'All 3 uploaded documents verified with 100% OCR match score',
      'Zero deficiencies, zero flags, active DBT PFMS disbursal',
      'Demonstrates the 100% confidence standard when all criteria are pristine',
    ],
  },
  {
    id: 'preset_ineligible_no_marks',
    name: 'Ineligible Applicant - Insufficient Marks (Submission Blocked)',
    badge: 'Ineligible (Fails Cutoff)',
    badgeColor: 'bg-rose-100 text-rose-800 border-rose-300',
    category: 'Statutory Eligibility Failure',
    description: 'Candidate (Ramesh Kumar Munda) scored 38.0% aggregate marks, failing the mandatory MoTA statutory cutoff of 55.0%. Submission is strictly blocked with ineligibility prohibition.',
    parameters: {
      incomeCeiling: 800000,
      marksThreshold: 55,
      totalSlots: 750,
      femaleQuota: 30,
    },
    additionalApplications: COHORT_INELIGIBLE_NO_MARKS,
    keyHighlights: [
      'Ramesh Kumar Munda: Scored 38.0% marks vs 55.0% statutory cutoff (-17.0% deficit)',
      'Statutorily blocked: Candidate cannot submit scholarship application',
      'Overall confidence capped at 20% with critical cutoff deficiency notice',
      'Submission button disabled with clear ineligibility statutory explanation',
    ],
  },
  {
    id: 'preset_fraud_wrong_docs',
    name: 'Wrong & Fraudulent Documents Detected (Severe Mismatches - 18% Confidence)',
    badge: '18% Confidence (Wrong Docs)',
    badgeColor: 'bg-amber-100 text-amber-800 border-amber-300',
    category: 'Forensic Integrity & Fraud Sentinel',
    description: 'Candidate (Deepak Verma) uploaded a commercial electricity power bill in place of a caste certificate, a forged private salary slip exceeding income limits, and 42% marksheet. Confidence reduced to 18%.',
    parameters: {
      incomeCeiling: 800000,
      marksThreshold: 55,
      totalSlots: 750,
      femaleQuota: 30,
    },
    additionalApplications: COHORT_FRAUD_WRONG_DOCUMENTS,
    keyHighlights: [
      'Deepak Verma: Commercial power bill uploaded in caste certificate slot (Severe Mismatch)',
      'Tampered income slip exceeds ₹8L ceiling by ₹6.5 Lakhs with unauthorized seal',
      'Overall confidence dropped to 18% with High Forensic Risk trigger',
      'Demonstrates drastic confidence reduction for wrong and fraudulent documents',
    ],
  },
  {
    id: 'preset_20pct_and_spectrum',
    name: '20% Cutoff Test & Graded Confidence Spectrum (100% to 20% Benchmark)',
    badge: '20% Cutoff Boundary',
    badgeColor: 'bg-indigo-100 text-indigo-800 border-indigo-300',
    category: 'Eligibility & Confidence Audit',
    description: 'Special benchmark cohort: Exactly 1 person 100% verified (Ananya Soren), 1 person at 20% confidence with critical discrepancies to test eligibility boundaries (Vikram Munda), and other scholars with calibrated mistake reductions (84%, 62%, 45%).',
    parameters: {
      incomeCeiling: 800000,
      marksThreshold: 55,
      totalSlots: 750,
      femaleQuota: 30,
    },
    additionalApplications: COHORT_20PCT_CONFIDENCE_SPECTRUM,
    keyHighlights: [
      'Person 1 (Ananya Soren): 100% verified confidence & 100% merit score (zero defects)',
      'Person 2 (Vikram Munda): Exactly 20% confidence to test eligibility pass/fail thresholds',
      'Small mistakes accurately deduct calibrated confidence percentages (84%, 62%, 45%)',
      'Instant re-evaluation across all 360 dossiers when moving statutory cutoff sliders',
    ],
  },
  {
    id: 'preset_national_saturation_2026',
    name: 'MoTA National Saturation Cohort (Central & Eastern India)',
    badge: 'National Intake (6 States)',
    badgeColor: 'bg-emerald-100 text-emerald-800 border-emerald-300',
    category: 'National Cohort Ingestion',
    description: 'Ingests dossiers across Telangana, Jharkhand, Odisha, Madhya Pradesh, Chhattisgarh, and Meghalaya. Covers Gond, Santhal, Kandha, Bhil, and Khasi communities.',
    parameters: {
      incomeCeiling: 800000,
      marksThreshold: 55,
      totalSlots: 750,
      femaleQuota: 30,
    },
    additionalApplications: COHORT_NATIONAL_SATURATION,
    keyHighlights: [
      'Ingests 6 comprehensive dossiers across Telangana, Jharkhand, Odisha, MP, CG, Meghalaya',
      'Validates statutory criteria for NFST (₹37k/mo JRF) and NOS (£9,900 UK allowance)',
      'Activates DBT active disbursals and official merit rankings',
      'Updates all 36 state clusters on the GIS map',
    ],
  },
  {
    id: 'preset_pvtg_affirmative_boost',
    name: 'PVTG Fast-Track & Vulnerable Tribes Quota (AP, MP, JH, OD)',
    badge: 'Affirmative Action (4 PVTGs)',
    badgeColor: 'bg-violet-100 text-violet-800 border-violet-300',
    category: 'Vulnerable Groups Priority',
    description: 'Ingests Particularly Vulnerable Tribal Group (PVTG) scholars: Chenchu (AP), Devika Gond (MP), Budhan Birhor (JH), and Oxford scholar Subarna Dongria Kondh (OD).',
    parameters: {
      incomeCeiling: 1000000,
      marksThreshold: 50,
      totalSlots: 850,
      femaleQuota: 35,
    },
    additionalApplications: COHORT_PVTG_SCHOLARS,
    keyHighlights: [
      'Ingests 4 distinguished PVTG scholars (Chenchu, Birhor, Baiga/Gond, Dongria Kondh)',
      'Includes Oxford University (QS #3) Ph.D unconditional admission holder',
      'Expands income limit to ₹10,00,000 for vulnerable forest tribal households',
      'Increases female quota to 35% across merit selection board',
    ],
  },
  {
    id: 'preset_northeast_hill_tribes',
    name: 'Northeast Himalayan ST Academic Surge (Nagaland, Mizoram, Arunachal, Sikkim)',
    badge: 'Northeast Region (4 States)',
    badgeColor: 'bg-teal-100 text-teal-800 border-teal-300',
    category: 'Regional Intake: North-East',
    description: 'Ingests high-merit tribal scholars from the North-Eastern hill states: Ao Naga (Nagaland), Mizo (Mizoram - Imperial College London), Monpa (Arunachal Pradesh), and Bhutia (Sikkim).',
    parameters: {
      incomeCeiling: 850000,
      marksThreshold: 55,
      totalSlots: 770,
      femaleQuota: 35,
    },
    additionalApplications: COHORT_NORTHEAST_SCHOLARS,
    keyHighlights: [
      'Ingests 4 scholars from Nagaland, Mizoram, Arunachal Pradesh, and Sikkim',
      'Includes Imperial College London (QS #6) seismic geotechnical engineering scholar',
      'Covers endangered language linguistics, high-altitude cryosphere, and biotechnology',
      'Populates Northeast zone geospatial clusters on the India map',
    ],
  },
  {
    id: 'preset_western_forest_corridor',
    name: 'Western Belt Forest & Desert STs (Rajasthan, Gujarat, Maharashtra)',
    badge: 'Western Region (3 States)',
    badgeColor: 'bg-amber-100 text-amber-800 border-amber-300',
    category: 'Regional Intake: West',
    description: 'Ingests scholars from the western tribal corridor: Sunita Meena (Rajasthan - Solar Tech), Jignesh Rathawa (Gujarat - Sacred Pithora Art), and Pratibha Warli (Maharashtra - ANU Canberra).',
    parameters: {
      incomeCeiling: 800000,
      marksThreshold: 55,
      totalSlots: 750,
      femaleQuota: 33,
    },
    additionalApplications: COHORT_WESTERN_BELT_SCHOLARS,
    keyHighlights: [
      'Ingests 3 scholars from Rajasthan, Gujarat, and Maharashtra',
      'Includes Australian National University (QS #30) unconditional admission holder',
      'Covers clean energy microgrids, sacred Pithora mural art, and indigenous sociology',
      'Updates western state data in all dashboards',
    ],
  },
  {
    id: 'preset_southern_pvtg_corridor',
    name: 'Southern Nilgiri & Nallamala Tribal Belt (Tamil Nadu, Kerala, Karnataka)',
    badge: 'Southern Region (3 States)',
    badgeColor: 'bg-cyan-100 text-cyan-800 border-cyan-300',
    category: 'Regional Intake: South',
    description: 'Ingests forest PVTG scholars from the southern biodiversity hotspots: Sinivasan Toda (Nilgiris, TN), Amina Kurumba (Attappadi, KL), and Basavaraj Jenu Kuruba (Mysuru, KA).',
    parameters: {
      incomeCeiling: 750000,
      marksThreshold: 52,
      totalSlots: 750,
      femaleQuota: 33,
    },
    additionalApplications: COHORT_SOUTHERN_BELT_SCHOLARS,
    keyHighlights: [
      'Ingests 3 scholars from Tamil Nadu, Kerala, and Karnataka',
      '100% PVTG cohort: Toda (Ooty), Kurumba (Attappadi), Jenu Kuruba (Nagarahole)',
      'Studies Shola-grassland conservation, indigenous millet nutrition, and wild apiculture',
      'Lights up southern states on GIS scholarship map',
    ],
  },
  {
    id: 'preset_northern_himalayan_st',
    name: 'Northern Frontier Alpine STs (Ladakh, J&K, Himachal, Uttarakhand)',
    badge: 'Northern Region (4 States/UTs)',
    badgeColor: 'bg-indigo-100 text-indigo-800 border-indigo-300',
    category: 'Regional Intake: North',
    description: 'Ingests high-altitude mountain scholars: Stanzin Changpa (Ladakh), Farida Gujjar (J&K), Vikram Gaddi (Himachal Pradesh), and Cambridge scholar Pooja Bhotia (Uttarakhand).',
    parameters: {
      incomeCeiling: 850000,
      marksThreshold: 55,
      totalSlots: 760,
      femaleQuota: 35,
    },
    additionalApplications: COHORT_NORTHERN_HIMALAYAN_SCHOLARS,
    keyHighlights: [
      'Ingests 4 scholars across Ladakh, J&K, Himachal Pradesh, and Uttarakhand',
      'Includes University of Cambridge (QS #2) Ph.D unconditional admission holder',
      'Covers Pashmina goat adaptation, transhumant mobile schools, and alpine pastures',
      'Populates high-altitude northern border territories on GIS map',
    ],
  },
];

/**
 * Generator for custom user-created presets with target states
 */
export function generateCustomPreset(config: {
  name: string;
  scheme: 'NFST' | 'NOS' | 'Both';
  incomeCeiling: number;
  marksThreshold: number;
  totalSlots: number;
  femaleQuota: number;
  selectedStates: string[];
  candidateCount: number;
}): PresetScenario {
  const {
    name,
    scheme,
    incomeCeiling,
    marksThreshold,
    totalSlots,
    femaleQuota,
    selectedStates,
    candidateCount,
  } = config;

  const states = selectedStates.length > 0
    ? selectedStates
    : ['Jharkhand', 'Odisha', 'Telangana', 'Madhya Pradesh', 'Meghalaya'];

  const generatedApplications: Application[] = [];

  const sampleFirstNames = [
    { name: 'Arjun', gender: 'Male' as const },
    { name: 'Rani', gender: 'Female' as const },
    { name: 'Sukhram', gender: 'Male' as const },
    { name: 'Anjali', gender: 'Female' as const },
    { name: 'Birsa', gender: 'Male' as const },
    { name: 'Meena', gender: 'Female' as const },
    { name: 'Somnath', gender: 'Male' as const },
    { name: 'Pooja', gender: 'Female' as const },
    { name: 'Mangal', gender: 'Male' as const },
    { name: 'Shanti', gender: 'Female' as const },
    { name: 'Chotu', gender: 'Male' as const },
    { name: 'Kavita', gender: 'Female' as const },
  ];

  for (let i = 0; i < candidateCount; i++) {
    const stateName = states[i % states.length];
    const stateMeta = MASTER_36_INDIAN_STATES.find((s) => s.name === stateName);
    const tribe = stateMeta?.primaryTribes[0] || 'Scheduled Tribe';
    const district = stateMeta?.districts[0] || `${stateName} Central`;
    const nameObj = sampleFirstNames[i % sampleFirstNames.length];
    const candidateScheme: SchemeType = scheme === 'Both' ? (i % 3 === 0 ? 'NOS' : 'NFST') : scheme;

    const appId = `app_custom_${Date.now()}_${i + 1}`;
    const appNum = `${candidateScheme}/2026/CP-${(i + 1).toString().padStart(3, '0')}`;
    const marks = Math.min(95, Math.max(56, marksThreshold + (i % 7) * 3 + 2));
    const income = Math.max(120000, incomeCeiling - (i % 5) * 80000 - 50000);

    const isFemale = nameObj.gender === 'Female';
    const meritScore = Math.min(99, Math.round(marks * 0.9 + (isFemale ? 4 : 0) + (income < 300000 ? 5 : 2)));

    const app: Application = {
      id: appId,
      applicationNumber: appNum,
      scheme: candidateScheme,
      submittedAt: new Date(Date.now() - i * 86400000).toISOString(),
      updatedAt: new Date().toISOString(),
      status: candidateScheme === 'NFST' && i === 0 ? 'dbt_active' : 'submitted',
      applicant: {
        fullName: `${nameObj.name} ${tribe.replace(/\s*\(.*\)/, '')}`,
        fatherName: `Rameshwar ${tribe.replace(/\s*\(.*\)/, '')}`,
        motherName: `Parvati Devi`,
        gender: nameObj.gender,
        dob: `199${7 + (i % 3)}-0${(i % 9) + 1}-1${(i % 8) + 1}`,
        aadhaarNumber: `XXXX-XXXX-${1000 + i * 111}`,
        mobile: `+91 94${100 + i * 20} ${10000 + i * 123}`,
        email: `${nameObj.name.toLowerCase()}.${tribe.toLowerCase().replace(/[^a-z]/g, '')}@tribal-edu.in`,
        stCommunity: tribe,
        state: stateName,
        district,
        pincode: '500001',
        domicileState: stateName,
        annualFamilyIncome: income,
        parentOccupation: 'Agriculture & Forest Minor Produce',
      },
      academic: {
        qualifyingDegree: candidateScheme === 'NOS' ? 'Master of Science (M.Sc)' : 'M.Sc / M.A Degree',
        qualifyingPercentage: marks,
        passingYear: 2024,
        institutionName: `State University of ${stateName}`,
        targetProgram: 'Ph.D',
        specialization: `Indigenous Resource Management & Tribal Studies`,
        researchTopic: `Sustainable community development and botanical preservation in ${district}`,
        ugcNetRollNo: `${stateMeta?.code || 'IN'}0100${2000 + i}`,
        ugcNetScore: Math.min(99, 88 + (i % 10)),
        ugcNetYear: '2024',
        isJrfQualified: candidateScheme === 'NFST',
        ...(candidateScheme === 'NOS' ? {
          foreignUniversityName: 'University of Melbourne, Australia',
          qsWorldRanking: 13,
        } : {}),
      },
      bankDetails: {
        accountHolderName: `${nameObj.name} ${tribe.replace(/\s*\(.*\)/, '')}`,
        accountNumber: `4910291${1000 + i}`,
        ifscCode: 'SBIN0001092',
        bankName: 'State Bank of India',
        branchName: `${district} Branch`,
        isAadhaarSeeded: true,
      },
      documents: [],
      aiAnalysis: {
        overallConfidence: 96,
        eligibilityPassed: true,
        requiresHumanReview: false,
        flags: isFemale ? ['Statutory Quota Priority: ST Female Scholar'] : [],
        riskScore: 'Low',
        meritScore,
        verifiedFieldsCount: 16,
        totalFieldsCount: 16,
        summary: `Custom preset applicant from ${stateName} (${tribe}). Verified income and qualifying marks.`,
      },
      deficiencies: [],
    };

    generatedApplications.push(app);
  }

  return {
    id: `preset_custom_${Date.now()}`,
    name,
    badge: 'Custom Ingestion',
    badgeColor: 'bg-indigo-100 text-indigo-800 border-indigo-300',
    category: 'User Custom Ingestion',
    description: `User-configured statutory preset covering ${states.length} state(s) with ${candidateCount} synthesized candidate dossier(s).`,
    parameters: {
      incomeCeiling,
      marksThreshold,
      totalSlots,
      femaleQuota,
    },
    additionalApplications: generatedApplications,
    keyHighlights: [
      `Ingests ${candidateCount} candidates across ${states.join(', ')}`,
      `Enforces ₹${(incomeCeiling / 100000).toFixed(1)} Lakhs income ceiling & ${marksThreshold}% marks cutoff`,
      `Applies ${femaleQuota}% statutory female reservation quota`,
      `Updates all 36 state clusters and active analytical tabs`,
    ],
  };
}

// Helper to evaluate a full dataset with given parameters
export function evaluateAllWithPreset(
  applications: Application[],
  params: {
    incomeCeiling: number;
    marksThreshold: number;
    totalSlots: number;
    femaleQuota: number;
  },
  rules: Record<SchemeType, SchemeRuleConfig>
): {
  updatedRules: Record<SchemeType, SchemeRuleConfig>;
  evaluatedApplications: Application[];
} {
  const updatedRules: Record<SchemeType, SchemeRuleConfig> = {
    ...rules,
    NFST: {
      ...rules.NFST,
      maxSlots: params.totalSlots,
      femaleReservationPercent: params.femaleQuota,
      eligibility: {
        ...rules.NFST.eligibility,
        minQualifyingPercentage: params.marksThreshold,
        maxIncomeLimit: params.incomeCeiling,
      },
    },
    NOS: {
      ...rules.NOS,
      femaleReservationPercent: params.femaleQuota,
      eligibility: {
        ...rules.NOS.eligibility,
        minQualifyingPercentage: params.marksThreshold,
        maxIncomeLimit: params.incomeCeiling,
      },
    },
  };

  const evaluatedApplications = applications.map((app) => {
    const schemeRule = updatedRules[app.scheme || 'NFST'];
    const evalResult = evaluateApplication(app, schemeRule);

    const applicantMarks = app.academic?.qualifyingPercentage ?? 0;
    const minMarks = schemeRule.eligibility.minQualifyingPercentage;
    const failsCutoff = applicantMarks < minMarks;

    const applicantIncome = app.applicant?.annualFamilyIncome ?? 0;
    const maxIncome = schemeRule.eligibility.maxIncomeLimit;
    const failsIncome = Boolean(maxIncome && applicantIncome > maxIncome);

    let status = app.status;
    let deficiencies = [...(app.deficiencies || [])];

    if (!evalResult.passed || failsCutoff || failsIncome) {
      status = 'flagged_deficiency';
      if (failsCutoff && !deficiencies.some(d => d.field === 'qualifyingPercentage')) {
        deficiencies.push({
          id: `def_cutoff_${Date.now()}_${app.id}`,
          field: 'qualifyingPercentage',
          title: 'Qualifying Score Below Scheme Cutoff',
          description: `Candidate scored ${applicantMarks}%, which is below the active ${app.scheme} statutory cutoff of ${minMarks}%.`,
          severity: 'critical',
          issuedAt: new Date().toISOString(),
          isResolved: false,
        });
      }
      if (failsIncome && !deficiencies.some(d => d.field === 'annualFamilyIncome')) {
        deficiencies.push({
          id: `def_inc_${Date.now()}_${app.id}`,
          field: 'annualFamilyIncome',
          title: 'Income Limit Exceeded',
          description: `Family income ₹${applicantIncome.toLocaleString('en-IN')} exceeds active statutory limit of ₹${maxIncome?.toLocaleString('en-IN')}.`,
          severity: 'critical',
          issuedAt: new Date().toISOString(),
          isResolved: false,
        });
      }
    } else {
      deficiencies = deficiencies.filter(d => d.field !== 'qualifyingPercentage' && d.field !== 'annualFamilyIncome');
      if (app.id === 'app_spec_100' || app.id === 'app_nfst_001' || app.status === 'dbt_active') {
        status = 'dbt_active';
      } else if (app.id === 'app_nos_002' || app.status === 'merit_listed') {
        status = 'merit_listed';
      } else if (app.status === 'approved') {
        status = 'approved';
      } else {
        status = status === 'submitted' ? 'in_scrutiny' : status;
      }
    }

    const updatedFlags = [...evalResult.flags];
    if (failsCutoff && !updatedFlags.some(f => f.includes('cutoff'))) {
      updatedFlags.unshift(`Qualifying percentage (${applicantMarks}%) is below cutoff of ${minMarks}%`);
    }
    if (failsIncome && !updatedFlags.some(f => f.includes('Income'))) {
      updatedFlags.unshift(`Annual family income exceeds cutoff ceiling of ₹${(maxIncome! / 100000).toFixed(1)}L`);
    }

    // Dynamic confidence adjustment when parameters shift
    let dynamicConfidence = evalResult.overallConfidence;
    if (failsCutoff) {
      const deficit = minMarks - applicantMarks;
      dynamicConfidence = Math.max(18, Math.min(dynamicConfidence, Math.round(48 - deficit * 3)));
    }
    if (failsIncome) {
      dynamicConfidence = Math.max(18, Math.min(dynamicConfidence, 42));
    }
    if (app.id === 'app_spec_020') {
      dynamicConfidence = 20; // Exactly 20% test candidate
    } else if (app.id === 'app_spec_100' && !failsCutoff && !failsIncome) {
      dynamicConfidence = 100; // Exactly 100% perfect candidate
    }

    return {
      ...app,
      status,
      deficiencies,
      aiAnalysis: {
        ...app.aiAnalysis,
        eligibilityPassed: evalResult.passed && !failsCutoff && !failsIncome,
        flags: updatedFlags,
        riskScore: (failsCutoff || failsIncome) ? 'High' : evalResult.riskScore,
        meritScore: evalResult.meritScore,
        overallConfidence: dynamicConfidence,
      },
      updatedAt: new Date().toISOString(),
    };
  });

  return { updatedRules, evaluatedApplications };
}
