import { Application, SchemeType, SchemeRuleConfig } from '../types/scholarship';
import { SEEDED_APPLICATIONS } from './mockData';
import { evaluateApplication } from './ruleEngine';
import { MASTER_36_INDIAN_STATES } from '../data/indianStates';

export interface PresetScenario {
  id: string;
  name: string;
  badge: string;
  badgeColor: string;
  category: string;
  description: string;
  parameters: {
    incomeCeiling: number;
    marksThreshold: number;
    totalSlots: number;
    femaleQuota: number;
  };
  additionalApplications: Application[];
  keyHighlights: string[];
}

// 1. Initial Baseline: STRICTLY EMPTY (Zero false/mock data before user adds preset)
export const BASELINE_APPLICATIONS: Application[] = [];

// 2. Curated Cohort A: National Saturation Cohort (6 applications across 6 states)
export const COHORT_NATIONAL_SATURATION: Application[] = [
  ...SEEDED_APPLICATIONS,
];

// 3. Curated Cohort B: PVTG Fast-Track (Particularly Vulnerable Tribal Groups)
export const COHORT_PVTG_SCHOLARS: Application[] = [
  {
    id: 'app_pvtg_001',
    applicationNumber: 'NFST/2026/PVTG-01',
    scheme: 'NFST',
    submittedAt: '2026-01-14T09:30:00Z',
    updatedAt: '2026-01-14T09:30:00Z',
    status: 'submitted',
    applicant: {
      fullName: 'Lingamaiah Chenchu',
      fatherName: 'Guruvaiah Chenchu',
      motherName: 'Venkatamma Chenchu',
      gender: 'Male',
      dob: '1997-05-14',
      aadhaarNumber: 'XXXX-XXXX-7123',
      mobile: '+91 94401 23456',
      email: 'lingamaiah.chenchu@anu.edu.in',
      stCommunity: 'Chenchu (PVTG)',
      state: 'Andhra Pradesh',
      district: 'Prakasam (Nallamala)',
      pincode: '523315',
      domicileState: 'Andhra Pradesh',
      annualFamilyIncome: 180000,
      parentOccupation: 'Minor Forest Produce Collector',
    },
    academic: {
      qualifyingDegree: 'M.Sc. in Botany',
      qualifyingPercentage: 73.2,
      passingYear: 2024,
      institutionName: 'Acharya Nagarjuna University, Guntur',
      targetProgram: 'Ph.D',
      specialization: 'Medicinal Flora of Nallamala Forest',
      researchTopic: 'Ethnobotanical documentation of rare medicinal plants used by Chenchu PVTG elders',
      ugcNetRollNo: 'AP01004921',
      ugcNetScore: 92.5,
      ugcNetYear: '2024',
      isJrfQualified: true,
    },
    bankDetails: {
      accountHolderName: 'Lingamaiah Chenchu',
      accountNumber: '49102910492',
      ifscCode: 'SBIN0002781',
      bankName: 'State Bank of India',
      branchName: 'Dornala Tribal Branch',
      isAadhaarSeeded: true,
    },
    documents: [],
    aiAnalysis: {
      overallConfidence: 96,
      eligibilityPassed: true,
      requiresHumanReview: false,
      flags: ['Affirmative Priority: Particularly Vulnerable Tribal Group (PVTG)'],
      riskScore: 'Low',
      meritScore: 94,
      verifiedFieldsCount: 16,
      totalFieldsCount: 16,
      summary: 'Verified PVTG candidate with high research relevance to indigenous botanical conservation.',
    },
    deficiencies: [],
  },
  {
    id: 'app_pvtg_002',
    applicationNumber: 'NFST/2026/PVTG-02',
    scheme: 'NFST',
    submittedAt: '2026-01-15T11:00:00Z',
    updatedAt: '2026-01-15T11:00:00Z',
    status: 'submitted',
    applicant: {
      fullName: 'Devika Gond',
      fatherName: 'Shambhu Gond',
      motherName: 'Kamla Gond',
      gender: 'Female',
      dob: '1998-10-21',
      aadhaarNumber: 'XXXX-XXXX-9932',
      mobile: '+91 97551 88412',
      email: 'devika.gond@bhu.ac.in',
      stCommunity: 'Gond',
      state: 'Madhya Pradesh',
      district: 'Dindori',
      pincode: '481880',
      domicileState: 'Madhya Pradesh',
      annualFamilyIncome: 240000,
      parentOccupation: 'Gond Art Artisan & Agriculture',
    },
    academic: {
      qualifyingDegree: 'M.A. in Indigenous History',
      qualifyingPercentage: 76.8,
      passingYear: 2024,
      institutionName: 'Banaras Hindu University (BHU)',
      targetProgram: 'Ph.D',
      specialization: 'Central Indian Tribal Rebellions & Oral Epics',
      researchTopic: 'Preservation of oral narrative traditions among Gond tribal bards (Pradhans)',
      ugcNetRollNo: 'MP03001844',
      ugcNetScore: 96.2,
      ugcNetYear: '2024',
      isJrfQualified: true,
    },
    bankDetails: {
      accountHolderName: 'Devika Gond',
      accountNumber: '58192019482',
      ifscCode: 'UBIN0531201',
      bankName: 'Union Bank of India',
      branchName: 'Dindori Branch',
      isAadhaarSeeded: true,
    },
    documents: [],
    aiAnalysis: {
      overallConfidence: 97,
      eligibilityPassed: true,
      requiresHumanReview: false,
      flags: ['Affirmative Priority: Female ST Researcher in Humanities'],
      riskScore: 'Low',
      meritScore: 95,
      verifiedFieldsCount: 16,
      totalFieldsCount: 16,
      summary: 'Distinguished female researcher in indigenous oral history. High UGC-NET score (96.2%).',
    },
    deficiencies: [],
  },
  {
    id: 'app_pvtg_003',
    applicationNumber: 'NFST/2026/PVTG-03',
    scheme: 'NFST',
    submittedAt: '2026-01-16T14:20:00Z',
    updatedAt: '2026-01-16T14:20:00Z',
    status: 'submitted',
    applicant: {
      fullName: 'Budhan Birhor',
      fatherName: 'Mangal Birhor',
      motherName: 'Champa Birhor',
      gender: 'Male',
      dob: '1999-02-18',
      aadhaarNumber: 'XXXX-XXXX-1982',
      mobile: '+91 93341 55219',
      email: 'budhan.birhor@cuj.ac.in',
      stCommunity: 'Birhor (PVTG)',
      state: 'Jharkhand',
      district: 'Khunti (Birsa Munda Land)',
      pincode: '835210',
      domicileState: 'Jharkhand',
      annualFamilyIncome: 140000,
      parentOccupation: 'Rope Making & Traditional Foraging',
    },
    academic: {
      qualifyingDegree: 'M.Sc. in Forestry & Wildlife',
      qualifyingPercentage: 71.5,
      passingYear: 2025,
      institutionName: 'Central University of Jharkhand',
      targetProgram: 'Ph.D',
      specialization: 'Canopy Ecology & Indigenous Forest Practices',
      researchTopic: 'Birhor traditional rope weaving using Bauhinia vahlii creeper and sustainability',
      ugcNetRollNo: 'JH02008129',
      ugcNetScore: 89.4,
      ugcNetYear: '2025',
      isJrfQualified: true,
    },
    bankDetails: {
      accountHolderName: 'Budhan Birhor',
      accountNumber: '61029104829',
      ifscCode: 'SBIN0001829',
      bankName: 'State Bank of India',
      branchName: 'Khunti Bazar Branch',
      isAadhaarSeeded: true,
    },
    documents: [],
    aiAnalysis: {
      overallConfidence: 95,
      eligibilityPassed: true,
      requiresHumanReview: false,
      flags: ['Affirmative Priority: Particularly Vulnerable Tribal Group (PVTG)'],
      riskScore: 'Low',
      meritScore: 91,
      verifiedFieldsCount: 16,
      totalFieldsCount: 16,
      summary: 'First-generation scholar from Birhor nomadic community. High ecological value research.',
    },
    deficiencies: [],
  },
  {
    id: 'app_pvtg_004',
    applicationNumber: 'NOS/2026/PVTG-04',
    scheme: 'NOS',
    submittedAt: '2026-01-17T16:45:00Z',
    updatedAt: '2026-01-17T16:45:00Z',
    status: 'submitted',
    applicant: {
      fullName: 'Subarna Kondh',
      fatherName: 'Dambarudhar Kondh',
      motherName: 'Malati Kondh',
      gender: 'Female',
      dob: '1997-08-04',
      aadhaarNumber: 'XXXX-XXXX-6192',
      mobile: '+91 94371 44102',
      email: 'subarna.kondh@oxford.alumni.org',
      stCommunity: 'Dongria Kondh (PVTG)',
      state: 'Odisha',
      district: 'Rayagada',
      pincode: '765001',
      domicileState: 'Odisha',
      annualFamilyIncome: 210000,
      parentOccupation: 'Horticulture in Niyamgiri Hills',
    },
    academic: {
      qualifyingDegree: 'M.Sc. in Sustainable Development',
      qualifyingPercentage: 81.4,
      passingYear: 2024,
      institutionName: 'Ravenshaw University, Cuttack',
      targetProgram: 'Ph.D',
      specialization: 'Indigenous Agroforestry Systems',
      researchTopic: 'Traditional agricultural biodiversity of Niyamgiri hills',
      foreignUniversityName: 'University of Oxford, United Kingdom',
      qsWorldRanking: 3,
    },
    bankDetails: {
      accountHolderName: 'Subarna Kondh',
      accountNumber: '29104819201',
      ifscCode: 'SBIN0000167',
      bankName: 'State Bank of India',
      branchName: 'Rayagada Main',
      isAadhaarSeeded: true,
    },
    documents: [],
    aiAnalysis: {
      overallConfidence: 98,
      eligibilityPassed: true,
      requiresHumanReview: false,
      flags: ['Affirmative Priority: Dongria Kondh PVTG', 'Prestigious QS Top 10 Admission'],
      riskScore: 'Low',
      meritScore: 98,
      verifiedFieldsCount: 16,
      totalFieldsCount: 16,
      summary: 'Exceptional Dongria Kondh female scholar holding unconditional Ph.D offer at University of Oxford (QS #3).',
    },
    deficiencies: [],
  },
];

// 4. Curated Cohort C: Northeast Himalayan ST Scholars (Nagaland, Mizoram, Arunachal Pradesh, Sikkim)
export const COHORT_NORTHEAST_SCHOLARS: Application[] = [
  {
    id: 'app_ne_001',
    applicationNumber: 'NFST/2026/NE-01',
    scheme: 'NFST',
    submittedAt: '2026-02-01T10:15:00Z',
    updatedAt: '2026-02-01T10:15:00Z',
    status: 'submitted',
    applicant: {
      fullName: 'Temjenrenla Ao',
      fatherName: 'Imnamerang Ao',
      motherName: 'Alemlemla Ao',
      gender: 'Female',
      dob: '1998-03-12',
      aadhaarNumber: 'XXXX-XXXX-4421',
      mobile: '+91 94360 88219',
      email: 'temjenrenla.ao@nagalanduniv.ac.in',
      stCommunity: 'Ao',
      state: 'Nagaland',
      district: 'Mokokchung',
      pincode: '798601',
      domicileState: 'Nagaland',
      annualFamilyIncome: 380000,
      parentOccupation: 'Education & Organic Farming',
    },
    academic: {
      qualifyingDegree: 'M.A. in Linguistics & Folkloristics',
      qualifyingPercentage: 78.5,
      passingYear: 2024,
      institutionName: 'Nagaland University, Lumami',
      targetProgram: 'Ph.D',
      specialization: 'Tibeto-Burman Endangered Languages',
      researchTopic: 'Acoustic phonetic documentation of endangered Mongsen Ao dialects',
      ugcNetRollNo: 'NL01002918',
      ugcNetScore: 97.1,
      ugcNetYear: '2024',
      isJrfQualified: true,
    },
    bankDetails: {
      accountHolderName: 'Temjenrenla Ao',
      accountNumber: '31092849102',
      ifscCode: 'SBIN0000137',
      bankName: 'State Bank of India',
      branchName: 'Mokokchung Main',
      isAadhaarSeeded: true,
    },
    documents: [],
    aiAnalysis: {
      overallConfidence: 97,
      eligibilityPassed: true,
      requiresHumanReview: false,
      flags: ['Affirmative Priority: North-East Female ST Scholar'],
      riskScore: 'Low',
      meritScore: 96,
      verifiedFieldsCount: 16,
      totalFieldsCount: 16,
      summary: 'Outstanding Ao Naga female linguist documenting critically endangered oral dialects.',
    },
    deficiencies: [],
  },
  {
    id: 'app_ne_002',
    applicationNumber: 'NOS/2026/NE-02',
    scheme: 'NOS',
    submittedAt: '2026-02-02T12:30:00Z',
    updatedAt: '2026-02-02T12:30:00Z',
    status: 'submitted',
    applicant: {
      fullName: 'Lalremruata Sailo',
      fatherName: 'C. Lalbiakzuala',
      motherName: 'Lalnunfeli Sailo',
      gender: 'Male',
      dob: '1997-11-25',
      aadhaarNumber: 'XXXX-XXXX-9102',
      mobile: '+91 94361 77123',
      email: 'lalremruata.sailo@mzu.edu.in',
      stCommunity: 'Mizo',
      state: 'Mizoram',
      district: 'Aizawl',
      pincode: '796004',
      domicileState: 'Mizoram',
      annualFamilyIncome: 420000,
      parentOccupation: 'Horticulture Department',
    },
    academic: {
      qualifyingDegree: 'M.Tech in Earthquake Geotechnical Engineering',
      qualifyingPercentage: 82.3,
      passingYear: 2024,
      institutionName: 'Mizoram University (MZU)',
      targetProgram: 'Ph.D',
      specialization: 'Seismic Hazards in Himalayan Fold Belts',
      foreignUniversityName: 'Imperial College London, United Kingdom',
      qsWorldRanking: 6,
    },
    bankDetails: {
      accountHolderName: 'Lalremruata Sailo',
      accountNumber: '48192019481',
      ifscCode: 'SBIN0001539',
      bankName: 'State Bank of India',
      branchName: 'Aizawl Main Branch',
      isAadhaarSeeded: true,
    },
    documents: [],
    aiAnalysis: {
      overallConfidence: 98,
      eligibilityPassed: true,
      requiresHumanReview: false,
      flags: ['QS Top 10 Offer', 'Critical Seismic Research for Himalayan Infrastructure'],
      riskScore: 'Low',
      meritScore: 97,
      verifiedFieldsCount: 16,
      totalFieldsCount: 16,
      summary: 'High-merit Mizo scholar holding unconditional Ph.D offer at Imperial College London (QS #6).',
    },
    deficiencies: [],
  },
  {
    id: 'app_ne_003',
    applicationNumber: 'NFST/2026/NE-03',
    scheme: 'NFST',
    submittedAt: '2026-02-03T14:00:00Z',
    updatedAt: '2026-02-03T14:00:00Z',
    status: 'submitted',
    applicant: {
      fullName: 'Tashi Wangdi Monpa',
      fatherName: 'Dorjee Monpa',
      motherName: 'Karma Monpa',
      gender: 'Male',
      dob: '1998-06-19',
      aadhaarNumber: 'XXXX-XXXX-3829',
      mobile: '+91 94362 11928',
      email: 'tashi.monpa@rgu.ac.in',
      stCommunity: 'Monpa',
      state: 'Arunachal Pradesh',
      district: 'Tawang',
      pincode: '790104',
      domicileState: 'Arunachal Pradesh',
      annualFamilyIncome: 290000,
      parentOccupation: 'High Altitude Agro-Pastoralism',
    },
    academic: {
      qualifyingDegree: 'M.Sc. in Glaciology & Himalayan Studies',
      qualifyingPercentage: 74.8,
      passingYear: 2024,
      institutionName: 'Rajiv Gandhi University (RGU), Doimukh',
      targetProgram: 'Ph.D',
      specialization: 'Glacial Lake Outburst Floods (GLOF) Early Warning',
      researchTopic: 'Cryospheric dynamics of Eastern Himalayan glaciers in Tawang and West Kameng',
      ugcNetRollNo: 'AR01001829',
      ugcNetScore: 93.6,
      ugcNetYear: '2024',
      isJrfQualified: true,
    },
    bankDetails: {
      accountHolderName: 'Tashi Wangdi Monpa',
      accountNumber: '29104928192',
      ifscCode: 'SBIN0005844',
      bankName: 'State Bank of India',
      branchName: 'Tawang Branch',
      isAadhaarSeeded: true,
    },
    documents: [],
    aiAnalysis: {
      overallConfidence: 96,
      eligibilityPassed: true,
      requiresHumanReview: false,
      flags: ['Border District Priority: Tawang', 'High Climate Relevance'],
      riskScore: 'Low',
      meritScore: 93,
      verifiedFieldsCount: 16,
      totalFieldsCount: 16,
      summary: 'Monpa scholar from border high-altitude region conducting vital Himalayan cryosphere studies.',
    },
    deficiencies: [],
  },
  {
    id: 'app_ne_004',
    applicationNumber: 'NFST/2026/NE-04',
    scheme: 'NFST',
    submittedAt: '2026-02-04T15:10:00Z',
    updatedAt: '2026-02-04T15:10:00Z',
    status: 'submitted',
    applicant: {
      fullName: 'Diki Ongmu Bhutia',
      fatherName: 'Sonam Bhutia',
      motherName: 'Pema Bhutia',
      gender: 'Female',
      dob: '1999-01-28',
      aadhaarNumber: 'XXXX-XXXX-8271',
      mobile: '+91 94340 33918',
      email: 'diki.bhutia@cus.ac.in',
      stCommunity: 'Bhutia',
      state: 'Sikkim',
      district: 'Mangan (North Sikkim)',
      pincode: '737116',
      domicileState: 'Sikkim',
      annualFamilyIncome: 350000,
      parentOccupation: 'Cardamom Cultivator',
    },
    academic: {
      qualifyingDegree: 'M.Sc. in Microbiology',
      qualifyingPercentage: 77.2,
      passingYear: 2025,
      institutionName: 'Sikkim University, Gangtok',
      targetProgram: 'Ph.D',
      specialization: 'Microbial Ecology of Traditional Fermented Foods',
      researchTopic: 'Metagenomic analysis of Kinema and Chhurpi traditional fermented bio-products',
      ugcNetRollNo: 'SK01004819',
      ugcNetScore: 95.8,
      ugcNetYear: '2025',
      isJrfQualified: true,
    },
    bankDetails: {
      accountHolderName: 'Diki Ongmu Bhutia',
      accountNumber: '39102948192',
      ifscCode: 'SBIN0000232',
      bankName: 'State Bank of India',
      branchName: 'Gangtok Main',
      isAadhaarSeeded: true,
    },
    documents: [],
    aiAnalysis: {
      overallConfidence: 97,
      eligibilityPassed: true,
      requiresHumanReview: false,
      flags: ['Affirmative Priority: Female ST Himalayan Scholar'],
      riskScore: 'Low',
      meritScore: 95,
      verifiedFieldsCount: 16,
      totalFieldsCount: 16,
      summary: 'Distinguished Bhutia female microbiologist studying indigenous Himalayan biotechnology.',
    },
    deficiencies: [],
  },
];

// 5. Curated Cohort D: Western Belt Forest Corridor (Rajasthan, Gujarat, Maharashtra)
export const COHORT_WESTERN_BELT_SCHOLARS: Application[] = [
  {
    id: 'app_west_001',
    applicationNumber: 'NFST/2026/WB-01',
    scheme: 'NFST',
    submittedAt: '2026-02-10T10:00:00Z',
    updatedAt: '2026-02-10T10:00:00Z',
    status: 'submitted',
    applicant: {
      fullName: 'Sunita Meena',
      fatherName: 'Ramkishan Meena',
      motherName: 'Kamla Devi Meena',
      gender: 'Female',
      dob: '1998-07-15',
      aadhaarNumber: 'XXXX-XXXX-5512',
      mobile: '+91 94140 66291',
      email: 'sunita.meena@uniraj.ac.in',
      stCommunity: 'Meena',
      state: 'Rajasthan',
      district: 'Banswara',
      pincode: '327001',
      domicileState: 'Rajasthan',
      annualFamilyIncome: 310000,
      parentOccupation: 'Agriculture & Livestock',
    },
    academic: {
      qualifyingDegree: 'M.Sc. in Renewable Energy Systems',
      qualifyingPercentage: 79.1,
      passingYear: 2024,
      institutionName: 'University of Rajasthan, Jaipur',
      targetProgram: 'Ph.D',
      specialization: 'Decentralized Solar Microgrids for Tribal Hamlets',
      researchTopic: 'Techno-economic feasibility of community solar storage in southern Rajasthan tribal belt',
      ugcNetRollNo: 'RJ01008491',
      ugcNetScore: 96.4,
      ugcNetYear: '2024',
      isJrfQualified: true,
    },
    bankDetails: {
      accountHolderName: 'Sunita Meena',
      accountNumber: '58192039182',
      ifscCode: 'SBIN0001524',
      bankName: 'State Bank of India',
      branchName: 'Banswara Main',
      isAadhaarSeeded: true,
    },
    documents: [],
    aiAnalysis: {
      overallConfidence: 97,
      eligibilityPassed: true,
      requiresHumanReview: false,
      flags: ['Female ST Scholar in Clean Tech'],
      riskScore: 'Low',
      meritScore: 96,
      verifiedFieldsCount: 16,
      totalFieldsCount: 16,
      summary: 'High-achieving female engineering scholar focusing on rural tribal solar energy transition.',
    },
    deficiencies: [],
  },
  {
    id: 'app_west_002',
    applicationNumber: 'NFST/2026/WB-02',
    scheme: 'NFST',
    submittedAt: '2026-02-11T11:20:00Z',
    updatedAt: '2026-02-11T11:20:00Z',
    status: 'submitted',
    applicant: {
      fullName: 'Jignesh Rathawa',
      fatherName: 'Pravin Rathawa',
      motherName: 'Narmadaben Rathawa',
      gender: 'Male',
      dob: '1999-04-03',
      aadhaarNumber: 'XXXX-XXXX-9912',
      mobile: '+91 98250 44192',
      email: 'jignesh.rathawa@msubaroda.ac.in',
      stCommunity: 'Rathawa',
      state: 'Gujarat',
      district: 'Chhota Udaipur',
      pincode: '391165',
      domicileState: 'Gujarat',
      annualFamilyIncome: 220000,
      parentOccupation: 'Pithora Tribal Art Painting & Agriculture',
    },
    academic: {
      qualifyingDegree: 'Master of Visual Arts (MVA)',
      qualifyingPercentage: 75.6,
      passingYear: 2024,
      institutionName: 'MS University of Baroda',
      targetProgram: 'Ph.D',
      specialization: 'Indigenous Visual Semiotics & Sacred Murals',
      researchTopic: 'Ritual iconography of Pithora sacred wall murals and heritage digitization',
      ugcNetRollNo: 'GJ02004819',
      ugcNetScore: 94.2,
      ugcNetYear: '2024',
      isJrfQualified: true,
    },
    bankDetails: {
      accountHolderName: 'Jignesh Rathawa',
      accountNumber: '48192019481',
      ifscCode: 'BARB0CHHOTA',
      bankName: 'Bank of Baroda',
      branchName: 'Chhota Udaipur Branch',
      isAadhaarSeeded: true,
    },
    documents: [],
    aiAnalysis: {
      overallConfidence: 96,
      eligibilityPassed: true,
      requiresHumanReview: false,
      flags: ['Master Pithora Tribal Artisan Scholar'],
      riskScore: 'Low',
      meritScore: 93,
      verifiedFieldsCount: 16,
      totalFieldsCount: 16,
      summary: 'Rathawa tribal artist scholar dedicated to preserving ancient Pithora sacred ritual art forms.',
    },
    deficiencies: [],
  },
  {
    id: 'app_west_003',
    applicationNumber: 'NOS/2026/WB-03',
    scheme: 'NOS',
    submittedAt: '2026-02-12T14:15:00Z',
    updatedAt: '2026-02-12T14:15:00Z',
    status: 'submitted',
    applicant: {
      fullName: 'Pratibha Warli',
      fatherName: 'Jivya Warli',
      motherName: 'Sitabai Warli',
      gender: 'Female',
      dob: '1997-09-11',
      aadhaarNumber: 'XXXX-XXXX-2019',
      mobile: '+91 98901 33201',
      email: 'pratibha.warli@tiss.edu',
      stCommunity: 'Warli',
      state: 'Maharashtra',
      district: 'Palghar',
      pincode: '401602',
      domicileState: 'Maharashtra',
      annualFamilyIncome: 280000,
      parentOccupation: 'Warli Art Artisan',
    },
    academic: {
      qualifyingDegree: 'M.A. in Social Anthropology',
      qualifyingPercentage: 80.2,
      passingYear: 2024,
      institutionName: 'Tata Institute of Social Sciences (TISS), Mumbai',
      targetProgram: 'Ph.D',
      specialization: 'Indigenous Ecology & Sacred Topography',
      foreignUniversityName: 'Australian National University (ANU), Australia',
      qsWorldRanking: 30,
    },
    bankDetails: {
      accountHolderName: 'Pratibha Warli',
      accountNumber: '59102948192',
      ifscCode: 'SBIN0000418',
      bankName: 'State Bank of India',
      branchName: 'Dahanu Road Branch',
      isAadhaarSeeded: true,
    },
    documents: [],
    aiAnalysis: {
      overallConfidence: 98,
      eligibilityPassed: true,
      requiresHumanReview: false,
      flags: ['Warli Female Scholar', 'Unconditional QS Top 50 Offer'],
      riskScore: 'Low',
      meritScore: 97,
      verifiedFieldsCount: 16,
      totalFieldsCount: 16,
      summary: 'Exceptional Warli indigenous researcher with unconditional admission at ANU Canberra (QS #30).',
    },
    deficiencies: [],
  },
];

// 6. Curated Cohort E: Southern Belt PVTG & Forest Tribes (Tamil Nadu, Kerala, Karnataka)
export const COHORT_SOUTHERN_BELT_SCHOLARS: Application[] = [
  {
    id: 'app_south_001',
    applicationNumber: 'NFST/2026/SB-01',
    scheme: 'NFST',
    submittedAt: '2026-02-15T09:40:00Z',
    updatedAt: '2026-02-15T09:40:00Z',
    status: 'submitted',
    applicant: {
      fullName: 'Sinivasan Toda',
      fatherName: 'Pillayar Toda',
      motherName: 'Ponni Toda',
      gender: 'Male',
      dob: '1998-05-22',
      aadhaarNumber: 'XXXX-XXXX-6612',
      mobile: '+91 94430 77192',
      email: 'sinivasan.toda@bharathiar.ac.in',
      stCommunity: 'Toda (PVTG)',
      state: 'Tamil Nadu',
      district: 'The Nilgiris (Ooty)',
      pincode: '643001',
      domicileState: 'Tamil Nadu',
      annualFamilyIncome: 190000,
      parentOccupation: 'Traditional Pastoral Buffalo Herder',
    },
    academic: {
      qualifyingDegree: 'M.Sc. in Environmental Sciences',
      qualifyingPercentage: 75.3,
      passingYear: 2024,
      institutionName: 'Bharathiar University, Coimbatore',
      targetProgram: 'Ph.D',
      specialization: 'Shola-Grassland High Altitude Ecology',
      researchTopic: 'Conservation ecology of Nilgiri Shola grasslands and Toda sacred groves',
      ugcNetRollNo: 'TN02003819',
      ugcNetScore: 94.7,
      ugcNetYear: '2024',
      isJrfQualified: true,
    },
    bankDetails: {
      accountHolderName: 'Sinivasan Toda',
      accountNumber: '48192019481',
      ifscCode: 'SBIN0000889',
      bankName: 'State Bank of India',
      branchName: 'Ooty Commercial Road',
      isAadhaarSeeded: true,
    },
    documents: [],
    aiAnalysis: {
      overallConfidence: 96,
      eligibilityPassed: true,
      requiresHumanReview: false,
      flags: ['Affirmative Priority: Toda PVTG Scholar'],
      riskScore: 'Low',
      meritScore: 94,
      verifiedFieldsCount: 16,
      totalFieldsCount: 16,
      summary: 'Toda PVTG scholar dedicated to conserving critical high-altitude Nilgiri Shola ecosystems.',
    },
    deficiencies: [],
  },
  {
    id: 'app_south_002',
    applicationNumber: 'NFST/2026/SB-02',
    scheme: 'NFST',
    submittedAt: '2026-02-16T11:00:00Z',
    updatedAt: '2026-02-16T11:00:00Z',
    status: 'submitted',
    applicant: {
      fullName: 'Amina Kurumba',
      fatherName: 'Ramanan Kurumba',
      motherName: 'Kamala Kurumba',
      gender: 'Female',
      dob: '1999-08-30',
      aadhaarNumber: 'XXXX-XXXX-1932',
      mobile: '+91 94471 22891',
      email: 'amina.kurumba@keralauniv.ac.in',
      stCommunity: 'Kurumba (PVTG)',
      state: 'Kerala',
      district: 'Palakkad (Attappadi)',
      pincode: '678581',
      domicileState: 'Kerala',
      annualFamilyIncome: 160000,
      parentOccupation: 'Attappadi Traditional Agro-Forestry',
    },
    academic: {
      qualifyingDegree: 'M.Sc. in Nutrition & Dietetics',
      qualifyingPercentage: 76.5,
      passingYear: 2024,
      institutionName: 'University of Kerala, Kariavattom',
      targetProgram: 'Ph.D',
      specialization: 'Indigenous Millets & Maternal Nutritional Health',
      researchTopic: 'Revitalizing traditional tribal millets (Ragi, Chama) for combating anemia in Attappadi hamlets',
      ugcNetRollNo: 'KL01004918',
      ugcNetScore: 95.1,
      ugcNetYear: '2024',
      isJrfQualified: true,
    },
    bankDetails: {
      accountHolderName: 'Amina Kurumba',
      accountNumber: '29104819201',
      ifscCode: 'SBIN0008620',
      bankName: 'State Bank of India',
      branchName: 'Agali Attappadi Branch',
      isAadhaarSeeded: true,
    },
    documents: [],
    aiAnalysis: {
      overallConfidence: 97,
      eligibilityPassed: true,
      requiresHumanReview: false,
      flags: ['Affirmative Priority: Kurumba PVTG Female Scholar'],
      riskScore: 'Low',
      meritScore: 95,
      verifiedFieldsCount: 16,
      totalFieldsCount: 16,
      summary: 'Kurumba PVTG female researcher pioneering indigenous tribal nutrition solutions in Attappadi.',
    },
    deficiencies: [],
  },
  {
    id: 'app_south_003',
    applicationNumber: 'NFST/2026/SB-03',
    scheme: 'NFST',
    submittedAt: '2026-02-17T13:30:00Z',
    updatedAt: '2026-02-17T13:30:00Z',
    status: 'submitted',
    applicant: {
      fullName: 'Basavaraj Jenu Kuruba',
      fatherName: 'Channappa Jenu Kuruba',
      motherName: 'Gowramma Jenu Kuruba',
      gender: 'Male',
      dob: '1998-12-05',
      aadhaarNumber: 'XXXX-XXXX-8821',
      mobile: '+91 94801 55291',
      email: 'basavaraj.kuruba@uni-mysore.ac.in',
      stCommunity: 'Jenu Kuruba (PVTG)',
      state: 'Karnataka',
      district: 'Mysuru (Hunsur)',
      pincode: '571105',
      domicileState: 'Karnataka',
      annualFamilyIncome: 175000,
      parentOccupation: 'Traditional Forest Honey Collector',
    },
    academic: {
      qualifyingDegree: 'M.Sc. in Entomology',
      qualifyingPercentage: 74.0,
      passingYear: 2024,
      institutionName: 'University of Mysore',
      targetProgram: 'Ph.D',
      specialization: 'Wild Apiculture & Pollinator Conservation',
      researchTopic: 'Apis dorsata giant rock bee nesting dynamics in Nagarahole tiger reserve canopy',
      ugcNetRollNo: 'KA03001928',
      ugcNetScore: 93.8,
      ugcNetYear: '2024',
      isJrfQualified: true,
    },
    bankDetails: {
      accountHolderName: 'Basavaraj Jenu Kuruba',
      accountNumber: '39102948192',
      ifscCode: 'SBIN0000845',
      bankName: 'State Bank of India',
      branchName: 'Hunsur Branch',
      isAadhaarSeeded: true,
    },
    documents: [],
    aiAnalysis: {
      overallConfidence: 96,
      eligibilityPassed: true,
      requiresHumanReview: false,
      flags: ['Affirmative Priority: Jenu Kuruba PVTG Scholar'],
      riskScore: 'Low',
      meritScore: 93,
      verifiedFieldsCount: 16,
      totalFieldsCount: 16,
      summary: 'Jenu Kuruba scholar applying generational traditional bee knowledge to wild pollinator conservation.',
    },
    deficiencies: [],
  },
];

// 7. Curated Cohort F: Northern Frontier & Himalayan STs (Ladakh, Jammu & Kashmir, Himachal, Uttarakhand)
export const COHORT_NORTHERN_HIMALAYAN_SCHOLARS: Application[] = [
  {
    id: 'app_north_001',
    applicationNumber: 'NFST/2026/NH-01',
    scheme: 'NFST',
    submittedAt: '2026-02-20T10:00:00Z',
    updatedAt: '2026-02-20T10:00:00Z',
    status: 'submitted',
    applicant: {
      fullName: 'Stanzin Dorje Changpa',
      fatherName: 'Tsering Changpa',
      motherName: 'Diskit Changpa',
      gender: 'Male',
      dob: '1998-04-18',
      aadhaarNumber: 'XXXX-XXXX-9912',
      mobile: '+91 94191 77281',
      email: 'stanzin.changpa@uol.ac.in',
      stCommunity: 'Changpa',
      state: 'Ladakh',
      district: 'Leh (Changthang)',
      pincode: '194101',
      domicileState: 'Ladakh',
      annualFamilyIncome: 240000,
      parentOccupation: 'Pashmina Goat Pastoralist',
    },
    academic: {
      qualifyingDegree: 'M.Sc. in High Altitude Animal Physiology',
      qualifyingPercentage: 75.8,
      passingYear: 2024,
      institutionName: 'University of Ladakh, Leh',
      targetProgram: 'Ph.D',
      specialization: 'Cold Desert Pastoral Adaptation & Pashmina Fiber Quality',
      researchTopic: 'Impact of climate change on winter forage and fiber yield in Changthang plateau',
      ugcNetRollNo: 'LA01001928',
      ugcNetScore: 94.6,
      ugcNetYear: '2024',
      isJrfQualified: true,
    },
    bankDetails: {
      accountHolderName: 'Stanzin Dorje Changpa',
      accountNumber: '48192019481',
      ifscCode: 'SBIN0001365',
      bankName: 'State Bank of India',
      branchName: 'Leh Main Branch',
      isAadhaarSeeded: true,
    },
    documents: [],
    aiAnalysis: {
      overallConfidence: 97,
      eligibilityPassed: true,
      requiresHumanReview: false,
      flags: ['High Altitude Ladakh Pastoralist Cohort'],
      riskScore: 'Low',
      meritScore: 94,
      verifiedFieldsCount: 16,
      totalFieldsCount: 16,
      summary: 'Changpa scholar from 14,000 ft Changthang high-altitude nomadic pastoral community.',
    },
    deficiencies: [],
  },
  {
    id: 'app_north_002',
    applicationNumber: 'NFST/2026/NH-02',
    scheme: 'NFST',
    submittedAt: '2026-02-21T11:45:00Z',
    updatedAt: '2026-02-21T11:45:00Z',
    status: 'submitted',
    applicant: {
      fullName: 'Farida Gujjar',
      fatherName: 'Choudhary Bashir Gujjar',
      motherName: 'Zainab Begum',
      gender: 'Female',
      dob: '1999-03-14',
      aadhaarNumber: 'XXXX-XXXX-4192',
      mobile: '+91 94190 44102',
      email: 'farida.gujjar@bgsbu.ac.in',
      stCommunity: 'Gujjar',
      state: 'Jammu and Kashmir',
      district: 'Rajouri',
      pincode: '185131',
      domicileState: 'Jammu and Kashmir',
      annualFamilyIncome: 210000,
      parentOccupation: 'Transhumant Pastoralism',
    },
    academic: {
      qualifyingDegree: 'M.A. in Rural Development & Economics',
      qualifyingPercentage: 78.2,
      passingYear: 2024,
      institutionName: 'BGSB University, Rajouri',
      targetProgram: 'Ph.D',
      specialization: 'Transhumant Tribal Migratory Routes & Education Access',
      researchTopic: 'Mobile seasonal schooling models for Gujjar-Bakarwal children during alpine migration',
      ugcNetRollNo: 'JK02008192',
      ugcNetScore: 96.0,
      ugcNetYear: '2024',
      isJrfQualified: true,
    },
    bankDetails: {
      accountHolderName: 'Farida Gujjar',
      accountNumber: '29104928192',
      ifscCode: 'JAKA0RAJOUR',
      bankName: 'Jammu and Kashmir Bank',
      branchName: 'Rajouri Main',
      isAadhaarSeeded: true,
    },
    documents: [],
    aiAnalysis: {
      overallConfidence: 97,
      eligibilityPassed: true,
      requiresHumanReview: false,
      flags: ['Affirmative Priority: Female Gujjar Scholar in J&K'],
      riskScore: 'Low',
      meritScore: 95,
      verifiedFieldsCount: 16,
      totalFieldsCount: 16,
      summary: 'Pioneering female Gujjar scholar advocating for seasonal pastoral educational policy.',
    },
    deficiencies: [],
  },
  {
    id: 'app_north_003',
    applicationNumber: 'NFST/2026/NH-03',
    scheme: 'NFST',
    submittedAt: '2026-02-22T14:10:00Z',
    updatedAt: '2026-02-22T14:10:00Z',
    status: 'submitted',
    applicant: {
      fullName: 'Vikram Gaddi',
      fatherName: 'Mansha Ram Gaddi',
      motherName: 'Kamla Devi Gaddi',
      gender: 'Male',
      dob: '1998-09-02',
      aadhaarNumber: 'XXXX-XXXX-7729',
      mobile: '+91 94180 55192',
      email: 'vikram.gaddi@hpuniv.ac.in',
      stCommunity: 'Gaddi',
      state: 'Himachal Pradesh',
      district: 'Chamba (Bharmour)',
      pincode: '176315',
      domicileState: 'Himachal Pradesh',
      annualFamilyIncome: 260000,
      parentOccupation: 'High Altitude Sheep & Goat Herder',
    },
    academic: {
      qualifyingDegree: 'M.Sc. in Botany & Mountain Ecology',
      qualifyingPercentage: 74.9,
      passingYear: 2024,
      institutionName: 'Himachal Pradesh University, Shimla',
      targetProgram: 'Ph.D',
      specialization: 'Alpine Pasture Ecology of Pir Panjal Range',
      researchTopic: 'Overgrazing dynamics vs climate shift in sub-alpine Bugyals of Bharmour tribal valley',
      ugcNetRollNo: 'HP01003819',
      ugcNetScore: 93.9,
      ugcNetYear: '2024',
      isJrfQualified: true,
    },
    bankDetails: {
      accountHolderName: 'Vikram Gaddi',
      accountNumber: '58192039182',
      ifscCode: 'SBIN0002319',
      bankName: 'State Bank of India',
      branchName: 'Bharmour Tribal Branch',
      isAadhaarSeeded: true,
    },
    documents: [],
    aiAnalysis: {
      overallConfidence: 96,
      eligibilityPassed: true,
      requiresHumanReview: false,
      flags: ['Bharmour ITDA Tribal Area Candidate'],
      riskScore: 'Low',
      meritScore: 93,
      verifiedFieldsCount: 16,
      totalFieldsCount: 16,
      summary: 'Gaddi mountain pastoralist researcher documenting sub-alpine alpine meadow ecology.',
    },
    deficiencies: [],
  },
  {
    id: 'app_north_004',
    applicationNumber: 'NOS/2026/NH-04',
    scheme: 'NOS',
    submittedAt: '2026-02-23T16:00:00Z',
    updatedAt: '2026-02-23T16:00:00Z',
    status: 'submitted',
    applicant: {
      fullName: 'Pooja Bhotia',
      fatherName: 'Dan Singh Bhotia',
      motherName: 'Parvati Bhotia',
      gender: 'Female',
      dob: '1997-12-14',
      aadhaarNumber: 'XXXX-XXXX-3310',
      mobile: '+91 94120 88192',
      email: 'pooja.bhotia@cam.ac.uk',
      stCommunity: 'Bhotia',
      state: 'Uttarakhand',
      district: 'Pithoragarh',
      pincode: '262545',
      domicileState: 'Uttarakhand',
      annualFamilyIncome: 340000,
      parentOccupation: 'Himalayan Herbal Collection & Weaving',
    },
    academic: {
      qualifyingDegree: 'M.Sc. in Pharmacology & Drug Discovery',
      qualifyingPercentage: 81.6,
      passingYear: 2024,
      institutionName: 'Kumaun University, Nainital',
      targetProgram: 'Ph.D',
      specialization: 'Bioactive Alkaloids from High-Altitude Alpine Flora',
      foreignUniversityName: 'University of Cambridge, United Kingdom',
      qsWorldRanking: 2,
    },
    bankDetails: {
      accountHolderName: 'Pooja Bhotia',
      accountNumber: '48192019481',
      ifscCode: 'SBIN0000698',
      bankName: 'State Bank of India',
      branchName: 'Pithoragarh Main',
      isAadhaarSeeded: true,
    },
    documents: [],
    aiAnalysis: {
      overallConfidence: 99,
      eligibilityPassed: true,
      requiresHumanReview: false,
      flags: ['QS Top 3 Cambridge Offer', 'Himalayan Pharmacology Specialist'],
      riskScore: 'Low',
      meritScore: 99,
      verifiedFieldsCount: 16,
      totalFieldsCount: 16,
      summary: 'Exceptional Bhotia female scholar with unconditional Ph.D offer at University of Cambridge (QS #2).',
    },
    deficiencies: [],
  },
];

// Curated Master Presets Available to Add One by One
export const PRESET_SCENARIOS: PresetScenario[] = [
  {
    id: 'preset_national_saturation_2026',
    name: 'MoTA National Saturation Cohort (Central & Eastern India)',
    badge: 'National Intake (6 States)',
    badgeColor: 'bg-emerald-100 text-emerald-800 border-emerald-300',
    category: 'National Cohort Ingestion',
    description: 'Ingests dossiers across Telangana, Jharkhand, Odisha, Madhya Pradesh, Chhattisgarh, and Meghalaya. Covers Gond, Santhal, Kandha, Bhil, and Khasi communities.',
    parameters: {
      incomeCeiling: 800000,
      marksThreshold: 55,
      totalSlots: 750,
      femaleQuota: 30,
    },
    additionalApplications: COHORT_NATIONAL_SATURATION,
    keyHighlights: [
      'Ingests 6 comprehensive dossiers across Telangana, Jharkhand, Odisha, MP, CG, Meghalaya',
      'Validates statutory criteria for NFST (₹37k/mo JRF) and NOS (£9,900 UK allowance)',
      'Activates DBT active disbursals and official merit rankings',
      'Updates all 36 state clusters on the GIS map',
    ],
  },
  {
    id: 'preset_pvtg_affirmative_boost',
    name: 'PVTG Fast-Track & Vulnerable Tribes Quota (AP, MP, JH, OD)',
    badge: 'Affirmative Action (4 PVTGs)',
    badgeColor: 'bg-violet-100 text-violet-800 border-violet-300',
    category: 'Vulnerable Groups Priority',
    description: 'Ingests Particularly Vulnerable Tribal Group (PVTG) scholars: Chenchu (AP), Devika Gond (MP), Budhan Birhor (JH), and Oxford scholar Subarna Dongria Kondh (OD).',
    parameters: {
      incomeCeiling: 1000000,
      marksThreshold: 50,
      totalSlots: 850,
      femaleQuota: 35,
    },
    additionalApplications: COHORT_PVTG_SCHOLARS,
    keyHighlights: [
      'Ingests 4 distinguished PVTG scholars (Chenchu, Birhor, Baiga/Gond, Dongria Kondh)',
      'Includes Oxford University (QS #3) Ph.D unconditional admission holder',
      'Expands income limit to ₹10,00,000 for vulnerable forest tribal households',
      'Increases female quota to 35% across merit selection board',
    ],
  },
  {
    id: 'preset_northeast_hill_tribes',
    name: 'Northeast Himalayan ST Academic Surge (Nagaland, Mizoram, Arunachal, Sikkim)',
    badge: 'Northeast Region (4 States)',
    badgeColor: 'bg-teal-100 text-teal-800 border-teal-300',
    category: 'Regional Intake: North-East',
    description: 'Ingests high-merit tribal scholars from the North-Eastern hill states: Ao Naga (Nagaland), Mizo (Mizoram - Imperial College London), Monpa (Arunachal Pradesh), and Bhutia (Sikkim).',
    parameters: {
      incomeCeiling: 850000,
      marksThreshold: 55,
      totalSlots: 770,
      femaleQuota: 35,
    },
    additionalApplications: COHORT_NORTHEAST_SCHOLARS,
    keyHighlights: [
      'Ingests 4 scholars from Nagaland, Mizoram, Arunachal Pradesh, and Sikkim',
      'Includes Imperial College London (QS #6) seismic geotechnical engineering scholar',
      'Covers endangered language linguistics, high-altitude cryosphere, and biotechnology',
      'Populates Northeast zone geospatial clusters on the India map',
    ],
  },
  {
    id: 'preset_western_forest_corridor',
    name: 'Western Belt Forest & Desert STs (Rajasthan, Gujarat, Maharashtra)',
    badge: 'Western Region (3 States)',
    badgeColor: 'bg-amber-100 text-amber-800 border-amber-300',
    category: 'Regional Intake: West',
    description: 'Ingests scholars from the western tribal corridor: Sunita Meena (Rajasthan - Solar Tech), Jignesh Rathawa (Gujarat - Sacred Pithora Art), and Pratibha Warli (Maharashtra - ANU Canberra).',
    parameters: {
      incomeCeiling: 800000,
      marksThreshold: 55,
      totalSlots: 750,
      femaleQuota: 33,
    },
    additionalApplications: COHORT_WESTERN_BELT_SCHOLARS,
    keyHighlights: [
      'Ingests 3 scholars from Rajasthan, Gujarat, and Maharashtra',
      'Includes Australian National University (QS #30) unconditional admission holder',
      'Covers clean energy microgrids, sacred Pithora mural art, and indigenous sociology',
      'Updates western state data in all dashboards',
    ],
  },
  {
    id: 'preset_southern_pvtg_corridor',
    name: 'Southern Nilgiri & Nallamala Tribal Belt (Tamil Nadu, Kerala, Karnataka)',
    badge: 'Southern Region (3 States)',
    badgeColor: 'bg-cyan-100 text-cyan-800 border-cyan-300',
    category: 'Regional Intake: South',
    description: 'Ingests forest PVTG scholars from the southern biodiversity hotspots: Sinivasan Toda (Nilgiris, TN), Amina Kurumba (Attappadi, KL), and Basavaraj Jenu Kuruba (Mysuru, KA).',
    parameters: {
      incomeCeiling: 750000,
      marksThreshold: 52,
      totalSlots: 750,
      femaleQuota: 33,
    },
    additionalApplications: COHORT_SOUTHERN_BELT_SCHOLARS,
    keyHighlights: [
      'Ingests 3 scholars from Tamil Nadu, Kerala, and Karnataka',
      '100% PVTG cohort: Toda (Ooty), Kurumba (Attappadi), Jenu Kuruba (Nagarahole)',
      'Studies Shola-grassland conservation, indigenous millet nutrition, and wild apiculture',
      'Lights up southern states on GIS scholarship map',
    ],
  },
  {
    id: 'preset_northern_himalayan_st',
    name: 'Northern Frontier Alpine STs (Ladakh, J&K, Himachal, Uttarakhand)',
    badge: 'Northern Region (4 States/UTs)',
    badgeColor: 'bg-indigo-100 text-indigo-800 border-indigo-300',
    category: 'Regional Intake: North',
    description: 'Ingests high-altitude mountain scholars: Stanzin Changpa (Ladakh), Farida Gujjar (J&K), Vikram Gaddi (Himachal Pradesh), and Cambridge scholar Pooja Bhotia (Uttarakhand).',
    parameters: {
      incomeCeiling: 850000,
      marksThreshold: 55,
      totalSlots: 760,
      femaleQuota: 35,
    },
    additionalApplications: COHORT_NORTHERN_HIMALAYAN_SCHOLARS,
    keyHighlights: [
      'Ingests 4 scholars across Ladakh, J&K, Himachal Pradesh, and Uttarakhand',
      'Includes University of Cambridge (QS #2) Ph.D unconditional admission holder',
      'Covers Pashmina goat adaptation, transhumant mobile schools, and alpine pastures',
      'Populates high-altitude northern border territories on GIS map',
    ],
  },
];

/**
 * Generator for custom user-created presets with target states
 */
export function generateCustomPreset(config: {
  name: string;
  scheme: 'NFST' | 'NOS' | 'Both';
  incomeCeiling: number;
  marksThreshold: number;
  totalSlots: number;
  femaleQuota: number;
  selectedStates: string[];
  candidateCount: number;
}): PresetScenario {
  const {
    name,
    scheme,
    incomeCeiling,
    marksThreshold,
    totalSlots,
    femaleQuota,
    selectedStates,
    candidateCount,
  } = config;

  const states = selectedStates.length > 0
    ? selectedStates
    : ['Jharkhand', 'Odisha', 'Telangana', 'Madhya Pradesh', 'Meghalaya'];

  const generatedApplications: Application[] = [];

  const sampleFirstNames = [
    { name: 'Arjun', gender: 'Male' as const },
    { name: 'Rani', gender: 'Female' as const },
    { name: 'Sukhram', gender: 'Male' as const },
    { name: 'Anjali', gender: 'Female' as const },
    { name: 'Birsa', gender: 'Male' as const },
    { name: 'Meena', gender: 'Female' as const },
    { name: 'Somnath', gender: 'Male' as const },
    { name: 'Pooja', gender: 'Female' as const },
    { name: 'Mangal', gender: 'Male' as const },
    { name: 'Shanti', gender: 'Female' as const },
    { name: 'Chotu', gender: 'Male' as const },
    { name: 'Kavita', gender: 'Female' as const },
  ];

  for (let i = 0; i < candidateCount; i++) {
    const stateName = states[i % states.length];
    const stateMeta = MASTER_36_INDIAN_STATES.find((s) => s.name === stateName);
    const tribe = stateMeta?.primaryTribes[0] || 'Scheduled Tribe';
    const district = stateMeta?.districts[0] || `${stateName} Central`;
    const nameObj = sampleFirstNames[i % sampleFirstNames.length];
    const candidateScheme: SchemeType = scheme === 'Both' ? (i % 3 === 0 ? 'NOS' : 'NFST') : scheme;

    const appId = `app_custom_${Date.now()}_${i + 1}`;
    const appNum = `${candidateScheme}/2026/CP-${(i + 1).toString().padStart(3, '0')}`;
    const marks = Math.min(95, Math.max(56, marksThreshold + (i % 7) * 3 + 2));
    const income = Math.max(120000, incomeCeiling - (i % 5) * 80000 - 50000);

    const isFemale = nameObj.gender === 'Female';
    const meritScore = Math.min(99, Math.round(marks * 0.9 + (isFemale ? 4 : 0) + (income < 300000 ? 5 : 2)));

    const app: Application = {
      id: appId,
      applicationNumber: appNum,
      scheme: candidateScheme,
      submittedAt: new Date(Date.now() - i * 86400000).toISOString(),
      updatedAt: new Date().toISOString(),
      status: candidateScheme === 'NFST' && i === 0 ? 'dbt_active' : 'submitted',
      applicant: {
        fullName: `${nameObj.name} ${tribe.replace(/\s*\(.*\)/, '')}`,
        fatherName: `Rameshwar ${tribe.replace(/\s*\(.*\)/, '')}`,
        motherName: `Parvati Devi`,
        gender: nameObj.gender,
        dob: `199${7 + (i % 3)}-0${(i % 9) + 1}-1${(i % 8) + 1}`,
        aadhaarNumber: `XXXX-XXXX-${1000 + i * 111}`,
        mobile: `+91 94${100 + i * 20} ${10000 + i * 123}`,
        email: `${nameObj.name.toLowerCase()}.${tribe.toLowerCase().replace(/[^a-z]/g, '')}@tribal-edu.in`,
        stCommunity: tribe,
        state: stateName,
        district,
        pincode: '500001',
        domicileState: stateName,
        annualFamilyIncome: income,
        parentOccupation: 'Agriculture & Forest Minor Produce',
      },
      academic: {
        qualifyingDegree: candidateScheme === 'NOS' ? 'Master of Science (M.Sc)' : 'M.Sc / M.A Degree',
        qualifyingPercentage: marks,
        passingYear: 2024,
        institutionName: `State University of ${stateName}`,
        targetProgram: 'Ph.D',
        specialization: `Indigenous Resource Management & Tribal Studies`,
        researchTopic: `Sustainable community development and botanical preservation in ${district}`,
        ugcNetRollNo: `${stateMeta?.code || 'IN'}0100${2000 + i}`,
        ugcNetScore: Math.min(99, 88 + (i % 10)),
        ugcNetYear: '2024',
        isJrfQualified: candidateScheme === 'NFST',
        ...(candidateScheme === 'NOS' ? {
          foreignUniversityName: 'University of Melbourne, Australia',
          qsWorldRanking: 13,
        } : {}),
      },
      bankDetails: {
        accountHolderName: `${nameObj.name} ${tribe.replace(/\s*\(.*\)/, '')}`,
        accountNumber: `4910291${1000 + i}`,
        ifscCode: 'SBIN0001092',
        bankName: 'State Bank of India',
        branchName: `${district} Branch`,
        isAadhaarSeeded: true,
      },
      documents: [],
      aiAnalysis: {
        overallConfidence: 96,
        eligibilityPassed: true,
        requiresHumanReview: false,
        flags: isFemale ? ['Statutory Quota Priority: ST Female Scholar'] : [],
        riskScore: 'Low',
        meritScore,
        verifiedFieldsCount: 16,
        totalFieldsCount: 16,
        summary: `Custom preset applicant from ${stateName} (${tribe}). Verified income and qualifying marks.`,
      },
      deficiencies: [],
    };

    generatedApplications.push(app);
  }

  return {
    id: `preset_custom_${Date.now()}`,
    name,
    badge: 'Custom Ingestion',
    badgeColor: 'bg-indigo-100 text-indigo-800 border-indigo-300',
    category: 'User Custom Ingestion',
    description: `User-configured statutory preset covering ${states.length} state(s) with ${candidateCount} synthesized candidate dossier(s).`,
    parameters: {
      incomeCeiling,
      marksThreshold,
      totalSlots,
      femaleQuota,
    },
    additionalApplications: generatedApplications,
    keyHighlights: [
      `Ingests ${candidateCount} candidates across ${states.join(', ')}`,
      `Enforces ₹${(incomeCeiling / 100000).toFixed(1)} Lakhs income ceiling & ${marksThreshold}% marks cutoff`,
      `Applies ${femaleQuota}% statutory female reservation quota`,
      `Updates all 36 state clusters and active analytical tabs`,
    ],
  };
}

// Helper to evaluate a full dataset with given parameters
export function evaluateAllWithPreset(
  applications: Application[],
  params: {
    incomeCeiling: number;
    marksThreshold: number;
    totalSlots: number;
    femaleQuota: number;
  },
  rules: Record<SchemeType, SchemeRuleConfig>
): {
  updatedRules: Record<SchemeType, SchemeRuleConfig>;
  evaluatedApplications: Application[];
} {
  const updatedRules: Record<SchemeType, SchemeRuleConfig> = {
    ...rules,
    NFST: {
      ...rules.NFST,
      maxSlots: params.totalSlots,
      femaleReservationPercent: params.femaleQuota,
      eligibility: {
        ...rules.NFST.eligibility,
        minQualifyingPercentage: params.marksThreshold,
        maxIncomeLimit: params.incomeCeiling,
      },
    },
    NOS: {
      ...rules.NOS,
      femaleReservationPercent: params.femaleQuota,
      eligibility: {
        ...rules.NOS.eligibility,
        minQualifyingPercentage: params.marksThreshold,
        maxIncomeLimit: params.incomeCeiling,
      },
    },
  };

  const evaluatedApplications = applications.map((app) => {
    const schemeRule = updatedRules[app.scheme || 'NFST'];
    const evalResult = evaluateApplication(app, schemeRule);

    let status = app.status;
    if (app.id === 'app_nfst_001' || app.status === 'dbt_active') {
      status = 'dbt_active';
    } else if (app.id === 'app_nos_002' || app.status === 'merit_listed') {
      status = 'merit_listed';
    } else if (app.status === 'approved') {
      status = 'approved';
    } else if (evalResult.passed) {
      status = status === 'submitted' ? 'in_scrutiny' : status;
    } else {
      status = 'flagged_deficiency';
    }

    return {
      ...app,
      status,
      aiAnalysis: {
        ...app.aiAnalysis,
        eligibilityPassed: evalResult.passed,
        flags: evalResult.flags,
        riskScore: evalResult.riskScore,
        meritScore: evalResult.meritScore,
        overallConfidence: evalResult.overallConfidence,
      },
      updatedAt: new Date().toISOString(),
    };
  });

  return { updatedRules, evaluatedApplications };
}
